### ISSUE TITLE
Support collect basic info like cpu, memory, GC eg..

### ISSUE THREAD

**Issue by zh6335901** [SkyAPM/SkyAPM-dotnet#108]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
Do you have any plan to support collect some basic info in the future? Like cpu, memory, io, GC eg..

**Comment by wu-sheng** [comment]
This is a good proposal, I think.

**Comment by liuhaoyang** [comment]
Will be available in the next release.
