### ISSUE TITLE
How you decide to use class member, not pull them from DI?

### ISSUE THREAD

**Issue by MaiReo** [SkyAPM/SkyAPM-dotnet#121]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
Why you design and use non-thread-safe class members such as ContextManager.StopSpan, 
which will crash production business code by throwing a InvalidException  with message "no active span"

I suggest to register your internal components with scoped lifestyle to the DI,
  then create scope for every context and use them.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
oap version: 6.0.0-beta , not important.
agent version: 0.6.0, offical nuget package.
.NET Runtime: .NET Core 2.2.0.100, with  meta package Microsoft.AspNetCore.App
- Which company or project?
Secret yet.
- What happen?
Agent crashes production business code. 
Agent throw a InvalidException when Calling DbContext.SaveChangeAsync
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
Even if ITraceContext controls the scope of the span through DI, the user may destroy the lifecycle of the TraceContext in an asynchronous manner (such as Task.Run..).
