### ISSUE TITLE
Please don't commit, reply issue with Chinese

### ISSUE THREAD

**Issue by rocketRobin** [SkyAPM/SkyAPM-dotnet#125]
![image](https://user-images.githubusercontent.com/9987850/51019494-1742dd80-15b6-11e9-9495-b2dadbb8b947.png)

This project is for everyone who use dotnet core, If you or your team or any developer use none-english,
this project will not become a real popular project, It will only popular in China, that not good for the project.

**Comment by wu-sheng** [comment]
Totally agree, comments/issues/documents all should be in English, just like SkyWalking Apache repo did.

**Comment by liuhaoyang** [comment]
Thank you for your feedback. We will strictly enforce the code review specification in the future.
