### ISSUE TITLE
Proxy pass http headers

### ISSUE THREAD

**Issue by ozonni** [SkyAPM/SkyAPM-dotnet#130]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
___
### Question
I have asp.net core microservice that receives http requests, does processing and then calls other microservices. Is it possible to take http headers from the request and proxy them for all http calls that are done in microservice?

**Comment by wu-sheng** [comment]
What do you mean proxy them for all calls?

**Comment by wu-sheng** [comment]
Where is your proxy? And what do you wants your proxy do?

**Comment by ozonni** [comment]
Let's say we have api1 and api2 microservice. 

1) api1 receives http request with header `x-header: 123`
2) api1 does processing and business logic
3) api1 calls api2 and sends http request and sets `x-header: 123`

It could be useful for distributed tracing where all the headers of original requests are passed through all chain of microservices calls.

**Comment by ozonni** [comment]
is it possible to do without touching and changing production code and have it done automatically by skywalking-netcore?

**Comment by wu-sheng** [comment]
If you are talking about trace context, such as trace id, you need to follow SkyWalking header protocol, then yes, it will propagate without changing codes. 

If you are talking about business context, such as order id, I think right now, SkyWalking hasn't provided such protocol yet.

**Comment by ozonni** [comment]
so, it is not possible with my custom headers but is possible with predefined SkyWalking headers, right? Is there a way to extend SkyWalking-netcore to support custom headers?

**Comment by wu-sheng** [comment]
Yes. For now. In theory, it is easy to extend, but we need to make sure the user scenarios are common.

May I ask, why do you want to propogate custom header? Which fields are you going to put in there.

**Comment by liuhaoyang** [comment]
One way is to support baggage in the agent without sending it to the backend, just spreading it in the business application. However, it should be noted that this will increase the load on the application. @wu-sheng what do you think?

**Comment by ozonni** [comment]
It could be pretty common thing, useful for other too.

Let's say you have an bunch of microservices involved in to the processing of the one request.
Client that send this request set application specific headers e.g. `x-order-id: 12345`. That this header value is used for logging. Would be cool if this header value is implicitly passed across all microservices and a tracing information.

**Comment by wu-sheng** [comment]
Would this be query in backend and UI? If it just shows in entry span tags or logs, should be easy, if we don't consider system extra payload, like @liuhaoyang said.

@liuhaoyang this is user payload, I am ok with adding this in protocol and java agent too. But how to use is my interest.

**Comment by wu-sheng** [comment]
If you asked for query, then, it is different. Because traces are saved in segment(include multiple spans), trace query is based on segment too.

**Comment by liuhaoyang** [comment]
@wu-sheng  in my experience, this is more of a business need than just tracking request performance.

**Comment by wu-sheng** [comment]
If analysis performance based on that, that is much more complex.

**Comment by snakorse** [comment]
@wu-sheng  the [Skywalking-Cross-Process-Correlation-Headers-Protocol](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Correlation-Headers-Protocol-v1.md) seems meet this, right?
