### ISSUE TITLE
Deploying data in IIS that is not monitored

### ISSUE THREAD

**Issue by 284247028** [SkyAPM/SkyAPM-dotnet#132]
can see the data using dotnet Xxx.dll,but deploying data in IIS that is not monitored.

How to configure if you want to deploy in IIS，tks

**Comment by liuhaoyang** [comment]
In the current version, there is no support for IIS. We can put it in the next milestone.

**Comment by 284247028** [comment]
tks

**Comment by icycore** [comment]
> [https://github.com/SkyAPM/SkyAPM-dotnet/issues/209](https://github.com/SkyAPM/SkyAPM-dotnet/issues/209)
my app under 0.9.0 runs well.

**Comment by ElderJames** [comment]
Please try to add a environment variable in web.config file.

```
<environmentVariables>
    <environmentVariable name="ASPNETCORE_HOSTINGSTARTUPASSEMBLIES" value="SkyAPM.Agent.AspNetCore" />
</environmentVariables>
```
