### ISSUE TITLE
SkyWalking Cross Process Propagation Headers Protocol V2

### ISSUE THREAD

**Issue by liuhaoyang** [SkyAPM/SkyAPM-dotnet#138]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

[SkyWalking Cross Process Propagation Headers Protocol v2](https://github.com/apache/incubator-skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v2.md) is also named as sw6 protocol. This protocol keeps the same purposes of v1(a.k.a. sw3), which is keep context propagation works.

**Comment by wu-sheng** [comment]
👍🏻👍🏻
