### ISSUE TITLE
asp.net core razor page 无法实现跟踪

### ISSUE THREAD

**Issue by jstzwhc** [SkyAPM/SkyAPM-dotnet#154]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jstzwhc** [comment]
asp.net core 2.2

**Comment by liuhaoyang** [comment]
Thank you for your feedback, we have added support for the razor page to the milestone.

**Comment by witskeeper** [comment]
i tested razor page in asp.net core 2.2
it works well

**Comment by liuhaoyang** [comment]
> 我在经过修复[＃157](https://github.com/SkyAPM/SkyAPM-dotnet/issues/157)后在asp.net core 2.2中测试了剃刀页面 服务页面中没有显示服务器摘要数据
> 
> 而且运作良好

Thanks for your test.
