### ISSUE TITLE
Optimized agent performance.

### ISSUE THREAD

**Issue by t674918085** [SkyAPM/SkyAPM-dotnet#156]
hi 柠檬，net core的探针性能问题啥时候能修复发版本呢

**Comment by liuhaoyang** [comment]
Hello, for English only

**Comment by t674918085** [comment]
hi Lemon, When  the performance problem of net core probe  can be repaired?

**Comment by liuhaoyang** [comment]
This issue has been solved. Refer to https://github.com/SkyAPM/SkyAPM-dotnet/pull/158.
