### ISSUE TITLE
No server summary data display in Service page

### ISSUE THREAD

**Issue by ChaunceyLin5152** [SkyAPM/SkyAPM-dotnet#157]
1. There is no server summery data displayed in Service page, but the avg data is correct.
2. OS information is incorrect, it displays the host name instead.
3.  The name is empty in Runing ServiceInstance.

Below is the server information for this issue:
Agent: 0.8.0
Collector: 6.0.0 GA
ES: 6.3.2
OS: CentOS 7.0 64bit
.NET Version: 2.1.403

**Comment by witskeeper** [comment]
2. OS information is incorrect, it displays the host name instead.
fixed in 6.1.0 GA 
https://github.com/apache/incubator-skywalking/issues/2196

**Comment by witskeeper** [comment]
1.There is no server summery data displayed in Service page, but the avg data is correct.
3.The name is empty in Runing ServiceInstance.
fixed in pull #160

**Comment by liuhaoyang** [comment]
> 1.服务页面中没有显示服务器夏季数据，但平均数据是正确的。
> 3. Runing ServiceInstance中的名称为空。
> 固定在拉[＃160](https://github.com/SkyAPM/SkyAPM-dotnet/pull/160)

Thank you for your fix.
