### ISSUE TITLE
Service health check

### ISSUE THREAD

**Issue by murdering** [SkyAPM/SkyAPM-dotnet#161]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
Do we have the health check function?
Our project wants a function to regularly check the service if it is healthy. If not, then trigger alarm to send email. Maybe it is like the health check function provided from Service Discovery tool "Consul".
It seems Skywalking is to monitor the services after received several requests. If no request coming, we don't know service if it is working fine, and the alarm will not be triggered.

Appreciate if you can correct my misunderstandings of Skywalking.

**Comment by liuhaoyang** [comment]
SkyWalking does not provide service health check feature similar to Consul.
