### ISSUE TITLE
Not able to build solution

### ISSUE THREAD

**Issue by hemant-learningforever** [SkyAPM/SkyAPM-dotnet#164]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question 
___
### Question
- I have downloaded source code from git and trying to build solution.
I am getting below error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SkyWalking' could not be found (are you missing a using directive or an assembly reference?)	SkyApm.Transport.Grpc	E:\SkyAPM-dotnet-0.8.0\SkyAPM-dotnet-0.8.0\src\SkyApm.Transport.Grpc\Common\SegmentV5Helpers.cs	23	Active

Can anybody assist?

**Comment by liuhaoyang** [comment]
First, you need to build `SkyApm.Transport.Grpc.Protocol`.

**Comment by hemant-learningforever** [comment]
I have done that. SkyApm.Transport.Grpc.Protocol is building successfully but while building SkyAPM.Transport.Grpc getting same build issue.

Basically its not able to find "using SkyWalking.NetworkProtocol;" where is this available?

**Comment by liuhaoyang** [comment]
Please refer to https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/appveyor.yml#L12. We will add the `how to build` docs later.

**Comment by hemant-learningforever** [comment]
Also as build order is already specified in solution. When i build it, this should be successful. Let me know if i am missing anything.

**Comment by hemant-learningforever** [comment]
Hi Liu,
I have refereed the yml specified above. I have used server specified there for nuget package still same issue.

Can you assist? Is this possible to have a live chat?

**Comment by liuhaoyang** [comment]
> Hi Liu,
> I have refereed the yml specified above. I have used server specified there for nuget package still same issue.
> 
> Can you assist? Is this possible to have a live chat?

Our QQ Group 392443393

**Comment by liuhaoyang** [comment]
@hemant-learningforever I have added build guide doc [how-to-build.md](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/docs/guides/how-to-build.md)

**Comment by hemant-learningforever** [comment]
@liuhaoyang  Thanks. This worked!
