### ISSUE TITLE
No executable found mathing command "dotnet-skyAPM"

### ISSUE THREAD

**Issue by hujingbao** [SkyAPM/SkyAPM-dotnet#165]
### Question
- First,i have run command like this:
`dotnet tool install -g SkyAPM.Dotnet.CLI`
i got this:
`Tool 'skyapm.dotnet.cli'  was successfully installed  `
- Then,i run this command:
`dotnet SkyAPM config sanple_app 192.168.1.202;11800`
i got this:
`No executable found mathing command "dotnet-skyAPM"`

PS:My system was ubuntu18.04 LTS
<img width="797" alt="SkyAPM-dotnet-issue" src="https://user-images.githubusercontent.com/15099511/54586944-7fe88380-4a59-11e9-920f-0ee239638501.png">

**Comment by hujingbao** [comment]
> ### Question
> * First,i have run command like this:
>   `dotnet tool install -g SkyAPM.Dotnet.CLI`
>   i got this:
>   `Tool 'skyapm.dotnet.cli'  was successfully installed  `
> * Then,i run this command:
>   `dotnet SkyAPM config sanple_app 192.168.1.202;11800`
>   i got this:
>   `No executable found mathing command "dotnet-skyAPM"`
> 
> PS:My system was ubuntu18.04 LTS
> <img alt="SkyAPM-dotnet-issue" width="797" src="https://user-images.githubusercontent.com/15099511/54586944-7fe88380-4a59-11e9-920f-0ee239638501.png">

**Comment by hujingbao** [comment]
> ### Question
> * First,i have run command like this:
>   `dotnet tool install -g SkyAPM.Dotnet.CLI`
>   i got this:
>   `Tool 'skyapm.dotnet.cli'  was successfully installed  `
> * Then,i run this command:
>   `dotnet SkyAPM config sanple_app 192.168.1.202;11800`
>   i got this:
>   `No executable found mathing command "dotnet-skyAPM"`
> 
> PS:My system was ubuntu18.04 LTS
> <img alt="SkyAPM-dotnet-issue" width="797" src="https://user-images.githubusercontent.com/15099511/54586944-7fe88380-4a59-11e9-920f-0ee239638501.png">

**Comment by liuhaoyang** [comment]
We can't reproduce your problem, please check user permission and dotnet sdk environment.

**Comment by hujingbao** [comment]
I have restarted  my system(ubuntu 18.04 LTS) and now it run successfully,thks!
