### ISSUE TITLE
What the fucking compile errors！！！

### ISSUE THREAD

**Issue by hujingbao** [SkyAPM/SkyAPM-dotnet#166]
__
### Bug
when i clone your master repos,and try to compile it,
I got those fuking errors!
like this:
<img width="1248" alt="fucking-errors" src="https://user-images.githubusercontent.com/15099511/54591910-38b4bf80-4a66-11e9-81d1-579cfd34970d.png">

**Comment by hujingbao** [comment]
https://github.com/SkyAPM/SkyAPM-dotnet/issues/164
I think you should write it in readme.md ......

**Comment by wu-sheng** [comment]
Please keep polite. This is the basic rule in open source.
