### ISSUE TITLE
when to support .net framework

### ISSUE THREAD

**Issue by 446690578** [SkyAPM/SkyAPM-dotnet#169]
Question
when to support .net framework and provide official documents? I saw that homePage provide nuget package but no Corresponding docs

**Comment by liuhaoyang** [comment]
It is anticipated that in version 1.0.0, we will have real asp.net monitoring capabilities.

**Comment by hemant-learningforever** [comment]
So As of now this skywalking apm for dotnet does not support monitring ASP.net applications. Is this correct?

For ASP.Net core does it monitors sql connections also?

**Comment by caozhiyuan** [comment]
under clr_profiler brach , in tools dir has SkyApm.DotNet.Installer_Sample.msi , install it can monitor asp.net program, and it's under develop . and only can run it in develop environment.

**Comment by hemant-learningforever** [comment]
ok. so i believe this will be migrated to master in milestone  v1.0.0

Does skywalking supports sql monitoring?

**Comment by liuhaoyang** [comment]
SkyWalking will support Database metrics and slow SQL tracing in version 6.1

**Comment by hemant-learningforever** [comment]
I see SqlClientTracingDiagnosticProcessor class in the current solution. What this does?
So As of now master branch code is supporting only asp.net core monitoring

**Comment by rumly** [comment]
If version 0.8 is not supported, please indicate it in a prominent place in the document. Thank you.
