### ISSUE TITLE
Questions about CAP integration

### ISSUE THREAD

**Issue by yang-xiaodong** [SkyAPM/SkyAPM-dotnet#177]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

This issue is transferred from https://github.com/dotnetcore/CAP/issues/306

---

Hi,

When I tried to integrate SkyWalking with CAP, found that can't find any trace records of the screenshots below mentioned in SW UI, 

![image](https://user-images.githubusercontent.com/11205717/55226495-0ff3ad80-5250-11e9-9483-4d9a33df058f.png)
---
just can see about http or db trace info

![image](https://user-images.githubusercontent.com/11205717/55227212-d3c14c80-5251-11e9-87cd-5d2b0c3917b1.png)

![image](https://user-images.githubusercontent.com/11205717/55227230-de7be180-5251-11e9-8ca3-b79f6721eb86.png)

here's how I integrated SW:
![image](https://user-images.githubusercontent.com/11205717/55227537-b771df80-5252-11e9-8db1-1d0e36f370ca.png)

how can I view the time consuming information about MQ send and consume and subscriber method execution.

Help pls.
Thank you in advance.

**Comment by yang-xiaodong** [comment]
@ajdwfnhaps

It looks like the CAP component is not working,  I can't see from your screenshot whether you reference the assembly `SkyApm.Diagnostics.CAP` ?

**Comment by ajdwfnhaps** [comment]
@yang-xiaodong 
Thanks, I just added reference the assembly SkyApm.Diagnostics.CAP , but seems not work.
![image](https://user-images.githubusercontent.com/11205717/55303870-46614080-547b-11e9-81cd-7b6aade64b1e.png)

seems no dependency injection about CAP was found in following screenshots
![image](https://user-images.githubusercontent.com/11205717/55303973-bec80180-547b-11e9-8d2e-3415dcd156bd.png)

@liuhaoyang  any recommend, thanks.

**Comment by liuhaoyang** [comment]
@yang-xiaodong You need to manually install and activate `SkyApm.Diagnostics.CAP`.
```
dotnet add package SkyAPM.Utilities.DependencyInjection
dotnet add package SkyAPM.Diagnostics.CAP
```

Then, add the following code in the `ConfigureService` method of the `Startup` class
```
services.AddSkyApmExtensions().AddCap();
```

**Comment by ajdwfnhaps** [comment]
@liuhaoyang 
Thanks, got it. now is working fine.
