### ISSUE TITLE
I couldn't find "SkyWalking.AspNetCore" package and services.AddSkyWalking

### ISSUE THREAD

**Issue by zhendl** [SkyAPM/SkyAPM-dotnet#191]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Question
- What do you want to know?

According the article: "https://www.codercto.com/a/24919.html"
I couldn't find "SkyWalking.AspNetCore" package and services.AddSkyWalking
            services.AddSkyWalking(option =>
            {
                option.ApplicationCode = "WebAPIService1";
                option.DirectServers = "localhost:11800";
            });
Is it work for now? Thank you.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
`SkyWalking.AspNetCore` is outdated, see https://github.com/SkyAPM/SkyAPM-dotnet#install-skywalking-net-core-agent

**Comment by StevenLiSiwei** [comment]
Hi, We are using Skywalking.AspNetCore for Skywalking 5.X.  It is very convenient to have programmatic al configuration done within the code. And our app is SCD and distributed to clients. Can I achieve this with latest SkyAPM-dotnet ?

`var app_code = Cache.IS_DEVELOPMENT_SERVER ? "[ServerTest]" : "[Server]";
            services.AddSkyWalking(options =>
            {
                options.ApplicationCode = app_code;
                options.DirectServers = "skywalking.revopos.io:11800";
            });`
