### ISSUE TITLE
Support for file system

### ISSUE THREAD

**Issue by hemant-learningforever** [SkyAPM/SkyAPM-dotnet#194]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 Feature or performance improvement

Is there a plan to support file system instrumentation?

Thanks,
Hemant.

**Comment by liuhaoyang** [comment]
Can you give a specific description of file system instrumentation?

**Comment by hemant-learningforever** [comment]
As an when i try to access a file through .net classes , can we get file name that is being accessed?
