### ISSUE TITLE
can not trace mysql with Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by jrlygdsj** [SkyAPM/SkyAPM-dotnet#198]
can not trace mysql with Pomelo.EntityFrameworkCore.MySql， i tried it .

**Comment by yang-xiaodong** [comment]
Please describe your environment and configuration information before reporting the issues so that we can quickly catch you, thanks

**Comment by jrlygdsj** [comment]
HttpClient trace is ok，but mysql not， environment and configuration information below：

windows 10,  nuget packages like below:
![image](https://user-images.githubusercontent.com/38058018/56776938-77762c00-6801-11e9-829b-307ba7bc0076.png),

skyapm.json ：

![image](https://user-images.githubusercontent.com/38058018/56777017-c4f29900-6801-11e9-9e1b-fac9b28129b5.png)


my test action:
![image](https://user-images.githubusercontent.com/38058018/56777085-17cc5080-6802-11e9-9e82-015ad6d1c14b.png)

**Comment by chenzhe** [comment]
me too

**Comment by ElderJames** [comment]
@yang-xiaodong Can you handle this issue?

**Comment by jinxinit** [comment]
我也遇到相同的问题，没有解决方案啊找不到

**Comment by snakorse** [comment]
Mybe this question has outdated, I can't reproduce the problem with the latest packages, gona be closed, feel free to reopen it or submit another issue if you still have problems.
