### ISSUE TITLE
HttpTracingHandler problem

### ISSUE THREAD

**Issue by king311247** [SkyAPM/SkyAPM-dotnet#199]
when i use  this code ,it's run successfully

![image](https://user-images.githubusercontent.com/10952874/56874581-5e71b300-6a6d-11e9-8676-c3ded080eec1.png)

but when is use below code,it's will thorw a expection
![image](https://user-images.githubusercontent.com/10952874/56874624-af81a700-6a6d-11e9-8ea5-8997b7efd528.png)

expection like this:
![image](https://user-images.githubusercontent.com/10952874/56874676-33d42a00-6a6e-11e9-861c-084ce5ce43c6.png)

if i remove the constructed function，run successed

**Comment by ElderJames** [comment]
I have fixed that in PR #270, if there are still have any problems,you can feel free to open another issue.
