### ISSUE TITLE
How to set muti SKYWALKING__SERVICENAME

### ISSUE THREAD

**Issue by clpgit** [SkyAPM/SkyAPM-dotnet#200]
I need to set multiple servicename。
How to set  SKYWALKING__SERVICENAME environment variable

**Comment by witskeeper** [comment]
more info please.
what is your os ?
.net core or framework?
and why you need this?

**Comment by caozhiyuan** [comment]
@clpgit  env can app base . such as :
1. commandline set SKYWALKING__SERVICENAME  environment , and run app
2. iis can use web.config or launchSettings.json set environment

or you can use skyapm.json

**Comment by jasen2002** [comment]
Framework4.6.1 Kuàngjià de web.Config bù zhīchí env shèzhì zěnme bàn ne
39/5000
What should I do if the web.config of the framework 4.6.1 framework does not support env settings?

**Comment by caozhiyuan** [comment]
@jasen2002  you can use skyapm.json
