### ISSUE TITLE
Does this application supports instrumenting any class?

### ISSUE THREAD

**Issue by hemant-learningforever** [SkyAPM/SkyAPM-dotnet#201]
Why do you submit this issue?
-  Question or discussion

___
### Question
- What do you want to know?
I see that skyapm is dependent on .net classes (sqlclient and httpclient) which exhibits some events and we are listening to these events to support instrumentation.

Is it provide a way to instrument any class other than .net supported classes?
is it using clrprofiler to support automatic instrumentation of any class?

Thanks,
Hemant.

**Comment by caozhiyuan** [comment]
@hemant-learningforever  this brach: https://github.com/SkyAPM/SkyAPM-dotnet/tree/coreclr_profiler

**Comment by hemant-learningforever** [comment]
@caozhiyuan  Thanks for information.
What is the plan to merge this to master and officially release it?

**Comment by hemant-learningforever** [comment]
Also can you explain how to run this app to monitor another app?

for e.g in case of master branch source code we run below commands
dotnet new mvc -n sampleapp
cd sampleapp
dotnet add package SkyAPM.Agent.AspNetCore
set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
set SKYWALKING__SERVICENAME=sample_app
dotnet run

what is the equivalent of this in coreclr_profiling branch?

**Comment by caozhiyuan** [comment]
@hemant-learningforever 

at roadmap , 1.0 may be merged to master , but may be long long time later

doc  https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/docs/develop.md
on windows install SkyApm.DotNet.Installer.msi , others set env 
releases assets : https://github.com/caozhiyuan/SkyAPM-dotnet/releases

**Comment by hemant-learningforever** [comment]
@caozhiyuan  Thank for all the answers. Really appreciated!

**Comment by hemant-learningforever** [comment]
Does this supports instrumenting any arbitary class? like streamwriter

**Comment by caozhiyuan** [comment]
@hemant-learningforever  yes , such as : static method, .cotr method , normal method. but some unsafe method params (native pointer ....) not support.
