### ISSUE TITLE
在framework4.6.1的项目中无法收集数据

### ISSUE THREAD

**Issue by jasen2002** [SkyAPM/SkyAPM-dotnet#202]
Hi，我的项目使用的是framework4.6.1，
引用nuget包SkyAPM.Agent.AspNet后，在项目中添加skyapm.json文件，
无其它操作，也没有设置环境变量（这个在framework是不是不用处理），生成项目后启动IIS。
在Sky Walking中的Service里能看到skyapm.json配置的ServiceName的应用，
但无请求URL的相关记录，我在浏览器中刷新了N多次也没有收集到相关数据。
希望得到您的答复。

**Comment by CsharpLeague** [comment]
您好实现了吗，我也在纠结这个问题

**Comment by hu372197979** [comment]
同上解决了 知会一声！

**Comment by hu372197979** [comment]
@liuhaoyang 能否给个framework4.6.1简要**配置说明**，是否需要配置环境变量，老项目想接入换成.netCore成本太高~~

**Comment by dcdlove** [comment]
我尝试下可以了写一个文档出来

**Comment by omegazeng** [comment]
有没有framework成功接入的，能给个安装配置文档吗，谢谢了!

**Comment by ElderJames** [comment]
We open a new issue(#269) to focus on issues related to the.net framework, and this issue will close.
If you have any questions, please refer to this issue #269 .
Thank you.

**Comment by ElderJames** [comment]
Asp.Net works well for now, please refer to the [SkyApm.Sample.AspNet](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet) project to adjust your dependency package.

**Comment by JiaZhenLin** [comment]
> Asp.Net目前运行良好，请参考[SkyApm.Sample.AspNet](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet)项目来调整依赖项包。

Asp.Net is not work
