### ISSUE TITLE
In skywalkingUi,Can only get trace logs, no access to services and topology maps

### ISSUE THREAD

**Issue by calanchenlins** [SkyAPM/SkyAPM-dotnet#203]
- [ ] skyapm.json
{ 
  "SkyWalking": {
    "ServiceName": "catalog_api",
    "Namespace": "ff",
    "HeaderVersions": [
      "sw6"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v6",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "oap:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000
      }
    }
  }
}

- [ ] Docker-compose
  catalog.api:
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
      - SKYWALKING__SERVICENAME=catalog_api
    ports:
      - "5101:80"

### there is oap log:
2019-05-13 14:25:42,472 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer -294489 [pool-15-thread-1] INFO  [] - Update mapping service id in the cache of service inventory, service id: 4, mapping service id: 0
- Please give me some advice

**Comment by zl33842901** [comment]
Hello, I had the same problem, How did you solve the problem?
