### ISSUE TITLE
use supervisor to start dotnetcore app,the agent will not start,and no logs in logs dir

### ISSUE THREAD

**Issue by ben900120** [SkyAPM/SkyAPM-dotnet#205]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
use supervisor to start dotnetcore app,the agent will not start,and no logs in logs dir.but start dotnetcore app in mannul,agent works.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
6.1 centos 7 dotnet 2.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Try running it using the `dotnet run` command.
