### ISSUE TITLE
Is "SkyAPM-dotnet" implemented on "IHostingStartup" and "IHostedService" basis?

### ISSUE THREAD

**Issue by cysnet** [SkyAPM/SkyAPM-dotnet#208]
### Question
- Is "SkyAPM-dotnet" implemented on "IHostingStartup" and "IHostedService" basis?

**Comment by liuhaoyang** [comment]
IHostedService is just the entry to the agent. If you want to understand the implementation of the `SkyAPM-dotnet`, you can refer to the following docs
- [Dapper, a Large-Scale Distributed Systems Tracing Infrastructure](https://research.google.com/archive/papers/dapper-2010-1.pdf)
- [SkyWalking Cross Process Propagation Headers Protocol](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v2.md)
- [DiagnosticSource User's Guide](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md)
