### ISSUE TITLE
项目发布到生产环境无法收集数据

### ISSUE THREAD

**Issue by jerry2000** [SkyAPM/SkyAPM-dotnet#209]
项目基于ABP平台，使用VS直接运行时可以收集数据，但是项目发布到生产环境后获取不到server、APPName等，也无法收集数据

**Comment by zfmy** [comment]
try to add this code to web.config

    <environmentVariables>
        <environmentVariable name="ASPNETCORE_HOSTINGSTARTUPASSEMBLIES" value="SkyAPM.Agent.AspNetCore" />
    </environmentVariables>

**Comment by ElderJames** [comment]
@zfmy have provided the solution. Thank @zfmy .
If there are still problems, just feel free to reopen this issue.
