### ISSUE TITLE
Unable to collect httpclient trace

### ISSUE THREAD

**Issue by quan01994** [SkyAPM/SkyAPM-dotnet#210]
When I use identityModel to get the token 
 
Sample code
````csharp
//services di
 services.AddHttpClient("Default")
                .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(new[]
                {
                    TimeSpan.FromSeconds(1),
                    TimeSpan.FromSeconds(2),
                    TimeSpan.FromSeconds(3)
                }));

// request
 private readonly HttpClient _httpClient;
 public VeimaIdentityService( IHttpClientFactory httpClientFactory)
 {
      _httpClient = httpClientFactory.CreateClient("Default");
 }
 var disco = await _httpClient.GetDiscoveryDocumentAsync(_configuration["VeimaIdentity:Url"]);
````
IdentityModel 3.10.10
SkyAPM.Agent.AspNetCore 0.8.0

![image](https://user-images.githubusercontent.com/20533465/59817135-445b9f00-9351-11e9-841e-ad68da55a86d.png)

in skywalking ui no any trace

**Comment by quan01994** [comment]
if i create httpclient not by name it can be collect

**Comment by caozhiyuan** [comment]
debug HttpClient DiagnosticsHandler and SkyApm HttpClientTracingDiagnosticProcessor

**Comment by quan01994** [comment]
(￣▽￣)" , how to debug...

**Comment by caozhiyuan** [comment]
rider or vs+resharper  enable source code debug

**Comment by quan01994** [comment]
Working normally,  

how to collect httpclient request parameters
