### ISSUE TITLE
Requirement for supporting mysql with MySqlConnector

### ISSUE THREAD

**Issue by wu-yafeng** [SkyAPM/SkyAPM-dotnet#213]
It seems there are mysql trace with `MySql.Data` but no MySqlConnector.

There are some bugs in `MySql.Data`,more information see [Connector .Net Errors - Exceptions (Doc ID 2223403.1)](https://support.oracle.com/knowledge/Oracle%20Database%20Products/2223403_1.html)

Any plan support mysql trace with MySqlConnector?

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
- Support `MySqlConnector`.

**Comment by leyou240** [comment]
+1

**Comment by ElderJames** [comment]
We are wating for PR mysql-net/MySqlConnector#493
Refer https://github.com/SkyAPM/SkyAPM-dotnet/issues/82#issuecomment-422010716

**Comment by wu-yafeng** [comment]
Hey,Is there any ETA?

**Comment by guochen2** [comment]
+1

**Comment by feiyun0112** [comment]
@ElderJames 

Can you talk about the current progress?
