### ISSUE TITLE
steps to install skywalk .Net agent supporting .Net framework

### ISSUE THREAD

**Issue by manojkumar542** [SkyAPM/SkyAPM-dotnet#215]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Steps to install skywalk .Net agent supporting .Net framework applications
what environment variable is needed to support the activation of the SkyAPM .NET  Agent targeting .Net framework applications.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by manojkumar542** [comment]
As dotnet run command doesn't support in .net framework so please guide me to setup skywalk .net APM agent with .net framework webapi

**Comment by liuhaoyang** [comment]
Please refer to https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet

**Comment by manojkumar542** [comment]
@liuhaoyang , what to know the environment variables to be added and how to run the .net framework application from command
