### ISSUE TITLE
Unable to run the .NET App after adding skyapm asp.net package to my project

### ISSUE THREAD

**Issue by manojkumar542** [SkyAPM/SkyAPM-dotnet#217]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
Added skyapm asp.net package and tried to run the application got the error from the attached snapshot
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
Skywalking 6.1
OS : windows 10 pro
.NET Runtime : 4.7.1
![Error](https://user-images.githubusercontent.com/40314203/60945667-d419bb00-a309-11e9-9eff-b732e9cbbdb5.PNG)

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by hu372197979** [comment]
使用 0.8.0版本可以解决这个错误？但还是会有其他坑等着你~~

**Comment by liuhaoyang** [comment]
The asp.net‘s complex and difficult dependency management mechanism has led to the fact that skyapm still has no out-of-the-box solution.

**Comment by alexforpc** [comment]
i can run in ver0.8,.netframework4.7.1,but it doesn't trace  sql  what processed in application.  my db is sqlserver 2008R2. how can i do to achieve trace sql of application.

**Comment by ElderJames** [comment]
We open a new issue(#269) to focus on issues related to the.net framework, and this issue will close.
If you have any questions, please refer to this issue #269 .
Thank you.

**Comment by ElderJames** [comment]
Asp.Net works well for now, please refer to the [SkyApm.Sample.AspNet](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet) project to adjust your dependency package.

**Comment by JiaZhenLin** [comment]
> Asp.Net目前运行良好，请参考[SkyApm.Sample.AspNet](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet)项目来调整依赖项包。

it not work

**Comment by dasajia2lang** [comment]
这个引用5.0 pre6的包可以解决
