### ISSUE TITLE
Unable to get DB stats from Skywalk UI in ASP .Net Core APP

### ISSUE THREAD

**Issue by manojkumar542** [SkyAPM/SkyAPM-dotnet#218]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Backend we are using dapper library to connect to MySQL server
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
Skywalking 6.1
Os - windows10pro
.NET Runtime - .netcoreapp2.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Not able to see DB stats even though my application is accessing MySQL DB , please check the attached image for reference
![metrics issue](https://user-images.githubusercontent.com/40314203/60956546-aab85980-a320-11e9-852b-302bbe9208db.PNG)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by manojkumar542** [comment]
@liuhaoyang , do we have any update on this?

**Comment by ElderJames** [comment]
@wu-sheng Can Skywalking UI collect database state?

**Comment by wu-sheng** [comment]
Yes, the backend could work if you set span layer as Database() and expected tags in the tags as following
1. DB_STATEMENT = "db.statement"
1. DB_TYPE = "db.type"

You could refer to codes directly.
1. For metrics of database access. https://github.com/apache/skywalking/blob/4e501328171f434c74144d373be6df0264f43a24/oap-server/server-receiver-plugin/skywalking-trace-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/trace/provider/parser/listener/endpoint/MultiScopesSpanListener.java#L230-L231
1. For slow SQL statement collection. https://github.com/apache/skywalking/blob/4e501328171f434c74144d373be6df0264f43a24/oap-server/server-receiver-plugin/skywalking-trace-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/trace/provider/parser/listener/endpoint/MultiScopesSpanListener.java#L185-L218

**Comment by jinxinit** [comment]
我也是，一直探测不到mysql的数据信息，要配置哪里呢，找了好几天了，没找到解决办法

**Comment by ElderJames** [comment]
@jinxinit Which ORM and driver did you use？

**Comment by jinxinit** [comment]
> @jinxinit Which ORM and driver did you use？

@ElderJames Hello，I use the following components:

<TargetFramework>netcoreapp2.1</TargetFramework>

  <PackageReference Include="Dapper.StrongName" Version="1.60.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2019.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
    <PackageReference Include="MySql.Data" Version="8.0.18" />

    <PackageReference Include="SkyAPM.Agent.AspNetCore" Version="0.9.0" />

Then  
Add skyapm.json,
Is there anything else it need to add to startup.cs or program.cs?
Have you solved it? 
Thank you very much！

**Comment by snakorse** [comment]
Currently, db sqls can be automatically traced only when you are using EntityFramework or SmartSql. If you are using MySql.Data directly or MySql.Data with other ORM frameworks like Dapper, I think the sql trace won't be collected.

**Comment by snakorse** [comment]
I'm going to close this because it's about an unsupported feature.
