### ISSUE TITLE
In the trace log, the log is redundant

### ISSUE THREAD

**Issue by littlehuihui** [SkyAPM/SkyAPM-dotnet#221]
In the trace log, the log is redundant
For example, the request executes a SQL through sqlClient, and two trace logs named "path" and "sqlclient" appear in the trace log.

Is this statistic from the two dimensions of request and SQL?

![image](https://user-images.githubusercontent.com/11981613/61575694-82d7ab80-ab01-11e9-8a05-9ce155b06a81.png)

**Comment by ElderJames** [comment]
You can try to select one service to filter the request list.

**Comment by wu-sheng** [comment]
@littlehuihui The list are segments not trace.
