### ISSUE TITLE
Miss SkyWalking.NetworkProtocol

### ISSUE THREAD

**Issue by 786744873** [SkyAPM/SkyAPM-dotnet#222]
the sourcecode in SkyApm.Transport.Grpc=>Common=>SegmentV6Helpers.cs.
in this class,
`using SkyWalking.NetworkProtocol;`,but I can't restore. Maybe missed this dll

**Comment by liuhaoyang** [comment]
refer to https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/docs/guides/how-to-build.md#build-from-github
