### ISSUE TITLE
netFrameWork

### ISSUE THREAD

**Issue by Yang-XL** [SkyAPM/SkyAPM-dotnet#224]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- .netFrameWork How To config ?
-.What should I do
-.Is there an example?

**Comment by alexforpc** [comment]
i try to run it on .net framework4.7.1 ,but the error of Nito.Async.Context showed, what can I do about this error? the other one,when i let this project run in .net core 2.1,all things are perfect. so if this project do not support .net framework?

**Comment by rickcoder** [comment]
same error on .net framework4.6.1

**Comment by omegazeng** [comment]
same error

**Comment by ElderJames** [comment]
We open a new issue(#269) to focus on issues related to the.net framework, and this issue will close.
If you have any questions, please refer to this issue #269 .
Thank you.

**Comment by ElderJames** [comment]
Asp.Net works well for now, please refer to the [SkyApm.Sample.AspNet](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet) project to adjust your dependency package.
