### ISSUE TITLE
Support Autofac

### ISSUE THREAD

**Issue by johnprice820** [SkyAPM/SkyAPM-dotnet#225]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking 6.2.0, Win10, netcoreapp2.2
___
### Requirement or improvement
Please consider support for Autofac dependency injection. 

I currently have multiple apps (GeneralHost) that do not use the .Net Core DI framework but are reliant on Autofac's DI framework. I attempted to manually add the required services but soon realized some classes where marked as internal and not accessible.

**Comment by wu-sheng** [comment]
Contributions are welcome.

**Comment by liuhaoyang** [comment]
You can use [adapter](https://github.com/autofac/Autofac.Extensions.DependencyInjection) to bridge from MS DI to Autofac

**Comment by ElderJames** [comment]
Generic Host also use IServiceCollection,you maybe can refer the solution for integrating Autofac to it.
