### ISSUE TITLE
Support for AOP capabilities

### ISSUE THREAD

**Issue by johnprice820** [SkyAPM/SkyAPM-dotnet#227]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
### Question
Does SkyAPM-dotnet support Aspect-oriented programming (AOP)?  If so, how do you enable it?

- Which version of SkyWalking, OS and .NET Runtime?
apache-skywalking-apm-6.2.0
Win10
netcoreapp2.2
___
### Requirement or improvement
We have found that the AOP capability in New Relic is it essential for us to use it. For example, once you turn on AOP you get a stack trace that tells times. We would like to know if this is available or possible with SkyAPM-dotnet, specifically for the SkyAPM.Agent.GeneralHost package.

**Comment by czd890** [comment]
Have a same requirements, 

or manual apis: https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace.md
