### ISSUE TITLE
Ali cloud Tracing Analysis Integrate

### ISSUE THREAD

**Issue by 491134648** [SkyAPM/SkyAPM-dotnet#228]
Seeing that Tracing Analysis on Ali Cloud has an introduction to the project's source engineering, how can I integrate into The Tracing Analysis on Ali Cloud?
Link
[https://help.aliyun.com/document_detail/90512.html?spm=a2c4g.11186623.6.583.5f8e6c3cCOHgOV](https://help.aliyun.com/document_detail/90512.html?spm=a2c4g.11186623.6.583.5f8e6c3cCOHgOV)

**Comment by wu-sheng** [comment]
This is the Ali Cloud commercial service. Ask them.
