### ISSUE TITLE
请问下skyapm支持.net core里监控redis么？

### ISSUE THREAD

**Issue by anmutu** [SkyAPM/SkyAPM-dotnet#230]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dcdlove** [comment]
要1.0正式版才有可能支持 希望出一个插件的例子这样就可以自己写了
https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/docs/roadmap.md

**Comment by ElderJames** [comment]
I intend to contribute the redis diagnostics via csredis  later this year 2881099/csredis/issues/186

**Comment by ElderJames** [comment]
Please turn to another issue #251
