### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by zhaoyingju** [SkyAPM/SkyAPM-dotnet#231]
the project ‘SkyApm.Transport.Grpc’  can‘t find namespace ’SkyWalking.NetworkProtocol‘；
this File：’SkyAPM-dotnet-master\src\SkyApm.Transport.Grpc\Common\SegmentV5Helpers.cs‘

**Comment by liuhaoyang** [comment]
refer to https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/docs/guides/how-to-build.md#build-from-github
