### ISSUE TITLE
How to manually monitor

### ISSUE THREAD

**Issue by fawdlstty** [SkyAPM/SkyAPM-dotnet#234]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I would like to know how to implement monitoring manually?For example, I manually collect CPU, memory data, or process HTTP (s) requests through TcpListener, and then monitor the number of requests per link.I did not use Asp.Net Core here, nor did I use any IoC. Could you please provide a document or example of manually collected data?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Provide ways to manually count data or refine documentation and examples

**Comment by liuhaoyang** [comment]
You can refer to [HostingDiagnosticProcessor](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Diagnostics.AspNetCore/HostingDiagnosticProcessor.cs)
