### ISSUE TITLE
请问一下。.netCore项目引用探针，但是UI无法获取到数据

### ISSUE THREAD

**Issue by sunchao809** [SkyAPM/SkyAPM-dotnet#235]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
.netCore项目引用探针，但是UI无法获取到数据
探针：SkyAPM.Agent.AspNetCore 使用 0.9.0
SkyWalking版本：6.3.0

![企业微信截图_15670707672263](https://user-images.githubusercontent.com/54343977/63928457-26fa2e00-ca82-11e9-9bae-6f56c81b6555.png)

![企业微信截图_15670708494432](https://user-images.githubusercontent.com/54343977/63928538-4e50fb00-ca82-11e9-9777-796055e54679.png)

![企业微信截图_15670710163098](https://user-images.githubusercontent.com/54343977/63928760-bacbfa00-ca82-11e9-8b60-6572832ccd1b.png)

![企业微信截图_15670710959320](https://user-images.githubusercontent.com/54343977/63928861-f070e300-ca82-11e9-9976-6bbace32f0df.png)

![企业微信截图_15670711181615](https://user-images.githubusercontent.com/54343977/63928868-f36bd380-ca82-11e9-99cb-deb6fce74a71.png)

application.yml （配置）
![企业微信截图_15670713751952](https://user-images.githubusercontent.com/54343977/63929147-89076300-ca83-11e9-92e0-e9c47e0820ac.png)

前台监控不到数据，这种情况是有什么原因？

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
Please check the configuration of the skywalking server address.
