### ISSUE TITLE
怎么捕获每个请求的输入响应数据

### ISSUE THREAD

**Issue by ohngahng** [SkyAPM/SkyAPM-dotnet#237]
比如post请求  用户提交了什么数据  然后api返回了什么json

**Comment by liuhaoyang** [comment]
你可以在[HostingDiagnosticProcessor](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Diagnostics.AspNetCore/HostingDiagnosticProcessor.cs)中进行扩展

**Comment by ElderJames** [comment]
@liuhaoyang have provided the solution.
If there are still problems, please feel free to reopen this issue.
