### ISSUE TITLE
请问一下，SkyApm中怎么捕获响应缓慢服务中函数调用的详细请求响应时间？

### ISSUE THREAD

**Issue by sunchao809** [SkyAPM/SkyAPM-dotnet#238]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
在日常请求过程中，我们不光是要找到服务与服务之间的请求响应数据，还需要知道当前服务为什么响应缓慢，SkyApm .netCore中能否捕获线程中函数调用的详细情况用于分析棘突问题，比如：
![企业微信截图_15676803708222](https://user-images.githubusercontent.com/54343977/64395769-f4f25880-d08d-11e9-9071-f5baeb2b13f3.png)

非常感谢大神们的解答
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
目前不支持函数级别的拦截和追踪。
