### ISSUE TITLE
请问一下，我想新增一个MySql.Data Agent,为什么测试没有进行拦截到

### ISSUE THREAD

**Issue by sunchao809** [SkyAPM/SkyAPM-dotnet#239]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
请问一下，我根据SqlClient进行仿照编辑的MySql.Data为什么没有拦截到，是什么原因引起的？

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
有demo或者相关日志看一下？

**Comment by ElderJames** [comment]
The premise is that MySql.Data supports DiagnosticSource.
