### ISSUE TITLE
两个服务部署在两台服务器，调用时为什么没有形成调用链

### ISSUE THREAD

**Issue by lihailong318** [SkyAPM/SkyAPM-dotnet#243]
A机器上部署服务1，B机器部署服务2，服务1中的接口调用了服务2

在A机器的浏览器调用服务1，最终形成的拓扑图是，user到服务1，user到服务2，
并没有体现服务1和服务2的关系

**Comment by liuhaoyang** [comment]
麻烦提供可以服务器环境和框架信息

**Comment by lihailong318** [comment]
两台机器都是win10系统，服务都是部署在iis上，配置的域名本地做的解析，用的.netframework4.6.1框架，skyapm.agent.aspnet 0.8.0版本，0.9.0版本报程序强签名错误。skywalking服务端是6.3.0版本



---原始邮件---
发件人: "Lemon"<notifications@github.com&gt;
发送时间: 2019年9月17日(星期二) 晚上10:17
收件人: "SkyAPM/SkyAPM-dotnet"<SkyAPM-dotnet@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"lihailong318"<1019067293@qq.com&gt;;
主题: Re: [SkyAPM/SkyAPM-dotnet] 两个服务部署在两台服务器，调用时为什么没有形成调用链 (#243)



麻烦提供可以服务器环境和框架信息

**Comment by ElderJames** [comment]
Did you pass the `HttpTracingHandler` instance while new a HttpClient?
As follow:
```
 var httpClient = new HttpClient(new HttpTracingHandler());
```

**Comment by miaojiuchen** [comment]
So the fx version HttpClient need to passing it a `HttpTracingHandler` and core version HttpClient don't need to do this right?

**Comment by ElderJames** [comment]
@miaojiuchen Exactly. You can refer to the sample projects.
- [Asp.Net](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/sample/SkyApm.Sample.AspNet)
- [Asp.Net Core](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/sample/SkyApm.Sample.Frontend/Controllers/ValuesController.cs#L27)

**Comment by ElderJames** [comment]
@lihailong318 So far, our Asp.Net sample works well, please use the lastest preview packages.
