### ISSUE TITLE
Service not shown in Skywalking UI using SkyAPM.Agent.AspNetCore. please help.

### ISSUE THREAD

**Issue by 12371601** [SkyAPM/SkyAPM-dotnet#244]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
  Bug

___
### Question
- What do you want to know?
How to use SkyAPM.Agent.AspNetCore  on Docker File  for docker to run asp.net core app?
Could you help us check our docker file?
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking: 6.1
OS: Centos 7
.NET Runtime: .net core 2.2

- Which company or project?
Chy company

- What happen?
Service not shown in Skywalking UI using SkyAPM.Agent.AspNetCore. please help.
[http://letyouknow.net/img/skyissue.jpg](url)
please check issue screenshot: http://letyouknow.net/img/skyissue.jpg
below is docker file:

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
RUN dotnet tool install -g SkyWalking.DotNet.CLI
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet skywalking install

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
COPY . .

FROM base AS final
ENV PATH="$PATH:/usr/local/share/dotnet/store"
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
ENV SKYWALKING__SERVICENAME=Lyn.Gateway
ENV DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore
COPY --from=build /usr/local/share/dotnet/store /usr/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/store /usr/local/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/x64 /usr/local/share/dotnet/x64
ENTRYPOINT ["dotnet", "Lyn.Gateway.dll"]

___
### Requirement or improvement
Help us check docker file.

**Comment by Lucky-Mi** [comment]
same issue, still don't know why

**Comment by 12371601** [comment]
focus on time-zone !!!
以下是我技术传承的公众号，欢迎扫码关注！

准开源高并发框架：http://agile.letyouknow.net
技术Blog：https://www.cnblogs.com/letyouknowdotnet/
技术网站：http://letyouknow.net/index.html




------------------ 原始邮件 ------------------
发件人: "Lucky-Mi"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 晚上11:32
收件人: "SkyAPM/SkyAPM-dotnet"<SkyAPM-dotnet@noreply.github.com>;
抄送: "12371601"<12371601@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [SkyAPM/SkyAPM-dotnet] Service not shown in Skywalking UI usingSkyAPM.Agent.AspNetCore. please help. (#244)




same issue, still don't know why

**Comment by DiweiL** [comment]
me too

**Comment by 12371601** [comment]
focus on timezone setting.




------------------ 原始邮件 ------------------
发件人: "DiweiL"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 中午11:17
收件人: "SkyAPM/SkyAPM-dotnet"<SkyAPM-dotnet@noreply.github.com>;
抄送: "12371601"<12371601@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [SkyAPM/SkyAPM-dotnet] Service not shown in Skywalking UI usingSkyAPM.Agent.AspNetCore. please help. (#244)




me too

**Comment by xiaochen20034** [comment]
ENV SKYWALKING__SERVICENAME=Lyn.Gateway
配置环境变量就好了

**Comment by ElderJames** [comment]
This issue seems to have been solved, I'll closed it.
