### ISSUE TITLE
如何在.netcore2.2通用主机里使用skyapm?

### ISSUE THREAD

**Issue by sd797994** [SkyAPM/SkyAPM-dotnet#246]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 我在nuget看到针对.netcore通用主机有一个apm包：SkyAPM.Agent.GeneralHost ，我尝试按照sample中SkyApm.Sample.GeneralHost项目的方式构建了一个自己的GeneralHost，引入包，并在HostBuilder添加了AddSkyAPM。接着我增加了一个我自定义的IHostedService，在StartAsync里通过HttpClient.GetAsync(http://xxx)，但是查询skywalking并没有产生链路追踪。然后我尝试在launchSettings引入环境变量，依然没有效果。
![image](https://user-images.githubusercontent.com/26075482/65844809-3a8f0200-e36a-11e9-98e8-29b7592fcbed.png)
![image](https://user-images.githubusercontent.com/26075482/65844815-45e22d80-e36a-11e9-9dfc-9493092787a5.png)
![image](https://user-images.githubusercontent.com/26075482/65844829-52668600-e36a-11e9-84cf-091d9d4bfcb4.png)

**Comment by ElderJames** [comment]
@pengweiqhca cc

**Comment by pengweiqhca** [comment]
参考SkyApm.Sample.GeneralHost

**Comment by ElderJames** [comment]
It work well,you can also check the log.
