### ISSUE TITLE
SkyWalking OAP 存储elasticsearch 数据时出现请求类型不正确？

### ISSUE THREAD

**Issue by sunchao809** [SkyAPM/SkyAPM-dotnet#247]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
请问一下，我布置k8s容器上的OAP服务，在存储elasticsearch是出现请求类型不正确导致数据没有存入ES中如图：
![image](https://user-images.githubusercontent.com/54343977/66697448-54382e00-ed08-11e9-9786-eaf6e9c4db13.png)

elasticsearch-client 日志如图：

![image](https://user-images.githubusercontent.com/54343977/66697465-7631b080-ed08-11e9-997a-31a4f618bf38.png)

elasticsearch-oss:6.7.0 （版本6.7.0）
skywalking-oap-server:6.4.0 （版本6.4.0）
请问一下，是否是ES与服务端版本不兼容？感谢各位的解答

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Please open another issue to [SkyWalking repo](https://github.com/apache/skywalking/issues/new).Thanks!
