### ISSUE TITLE
[疑问]追踪数据丢失？

### ISSUE THREAD

**Issue by yuefengkai** [SkyAPM/SkyAPM-dotnet#250]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 追踪数据丢失？
从追踪列表来看此请求用时 151365 ms 但详细列表中名没有很耗时的请求，查看k8s skyapm日志发现有异常，不知是否是异常导致没有详细数据？
![image](https://user-images.githubusercontent.com/2100585/67140602-b1932880-f28e-11e9-8814-f1c016120af3.png)

![image](https://user-images.githubusercontent.com/2100585/67140586-7c86d600-f28e-11e9-8731-ed2d547cacff.png)
![image](https://user-images.githubusercontent.com/2100585/67140623-046ce000-f28f-11e9-950f-76ee90c2e81d.png)

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
aliyun k8s
net core 2.2

skywalking 在 docker中 使用版本6.4.0
https://github.com/apache/skywalking-docker/blob/master/6/6.4/compose/docker-compose.yml
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Please provide a reproducible demo.

**Comment by ElderJames** [comment]
Please recheck the nightly build.
