### ISSUE TITLE
Support for FreeSql and CSRedis

### ISSUE THREAD

**Issue by 519544044** [SkyAPM/SkyAPM-dotnet#251]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
目前.net core版本下的FreeSql ORM和CSRedis 比较强大灵活，希望给予支持。

**Comment by ElderJames** [comment]
Hi  @2881099 , can we get any help from you?

**Comment by 2881099** [comment]
@ElderJames yes, any help

**Comment by ElderJames** [comment]
@2881099 That's great! We look forward to your progress, thank you!

**Comment by 2881099** [comment]
FreeSql 接入 Apache SkyWalking SkyApm 总结
https://github.com/2881099/FreeSql/issues/222

@519544044 @ElderJames

**Comment by landonzeng** [comment]
the code merge in?I didn't see in the master

**Comment by landonzeng** [comment]
> @2881099 That's great! We look forward to your progress, thank you!

the code merge in?I didn't see in the master

**Comment by wu-sheng** [comment]
@2881099 建议直接通过pull request 提交相关插件。

**Comment by landonzeng** [comment]
> FreeSql 接入 Apache SkyWalking SkyApm 总结
> [dotnetcore/FreeSql#222](https://github.com/dotnetcore/FreeSql/issues/222)
> 
> @519544044 @ElderJames

根据#222配置了，但是skywalking中的追踪并没有sql语句的记录
