### ISSUE TITLE
What is LocalSegmentContextAccessor class for?

### ISSUE THREAD

**Issue by xiaguoli** [SkyAPM/SkyAPM-dotnet#252]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/10445205/67351638-94a57080-f580-11e9-89eb-6f4adff894ad.png)

What is LocalSegmentContextAccessor class for？
_parent What does this field do？

**Comment by ElderJames** [comment]
Please see the doc [Trace-Data-Protocol](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Trace-Data-Protocol-v2.md#step-2-send-trace-and-metrics).
