### ISSUE TITLE
请问支持 6.4 版本吗

### ISSUE THREAD

**Issue by TomasPeng90s** [SkyAPM/SkyAPM-dotnet#253]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
我使用的是docker hub上的 skywalking-oa-server 和 skywalking-ui, 
项目中用 nuget 安装了SkyAPM.Agent.AspNetCore 做测试,数据能正常上报,
![image](https://user-images.githubusercontent.com/25027712/68463710-35b34d00-024a-11ea-9ea9-92dc98605640.png)

但是在仪表盘/拓扑图中却没有显示
![image](https://user-images.githubusercontent.com/25027712/68463761-57143900-024a-11ea-8720-42e22353b99e.png)

我的配置如下
![image](https://user-images.githubusercontent.com/25027712/68463883-85921400-024a-11ea-9fd7-fbed2645293f.png)

![image](https://user-images.githubusercontent.com/25027712/68463794-60050a80-024a-11ea-8ea5-bdc9b5987fbf.png)

是少配了什么造成的吗?

**Comment by czd890** [comment]
支持6.4，检查时区，查询的时候你先把时间往前和后多选择几天。
然后到 logs/skyapm-20191112.log查看日志，
看看时候已经把trace提交了。类似日志
```shell
SkyApm.Transport.Grpc.V6.SegmentReporter : Report 5 trace segment. cost: 00:00:00.3793201s
```
