### ISSUE TITLE
Database相关信息没有数据

### ISSUE THREAD

**Issue by xflag** [SkyAPM/SkyAPM-dotnet#254]
用SmartSql访问数据库，用Mysql驱动连接TiDB数据库，在Trace里可以看到SmartSql的追踪数据，但Database dashboard里的response time,Throughout,SLA,Percent等数据都没有，是什么原因呢？
![微信截图_20191108175552](https://user-images.githubusercontent.com/3249626/68467374-0522e180-0251-11ea-8e33-20522f5d326c.png)

**Comment by ElderJames** [comment]
@Ahoo-Wang cc

**Comment by Ahoo-Wang** [comment]
The SmartSql component is not explicitly mapped to a specific DB type, so there is no way to map the server (it can only be determined at startup).

@wu-sheng Oh, do you have any good suggestions?

**Comment by ElderJames** [comment]
Please turn to another issue #218
