### ISSUE TITLE
Use 'IOptionsMonitor<ConfigModel>', support for options hot updates.

### ISSUE THREAD

**Issue by czd890** [SkyAPM/SkyAPM-dotnet#255]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Feature or performance improvement

Use 'IOptionsMonitor<ConfigModel>' on ctor DI, and  subscribe the onchange event of options, support for options hot updates.

**Comment by feiyun0112** [comment]
@czd890 
which options need hot updates?
