### ISSUE TITLE
.netcore通过dotnet publish编译的程序，无法通过skywalking收集信息？

### ISSUE THREAD

**Issue by Caesar0630** [SkyAPM/SkyAPM-dotnet#257]
1、如果将.netcore项目发布到IIS，同样web.config中添加下面这句话，就可以收集到数据；
`<environmentVariables>`
`			<environmentVariable name="ASPNETCORE_HOSTINGSTARTUPASSEMBLIES" value="SkyAPM.Agent.AspNetCore" />`
`</environmentVariables>`
2、如果将.netcore项目通过dotnet publish命令编译后的程序包发布到服务器，在项目的web.config中也添加了上面那句话，不知道为什么就是收集不了数据？
![QQ截图20191114151013](https://user-images.githubusercontent.com/52985527/68834907-d5ad2280-06f1-11ea-9e05-58fc7a0876f3.png)

**Comment by ElderJames** [comment]
Please read the [offical docs about configuration with web.config](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#configuration-with-webconfig).

If there still have problems,you can feel free to reopen this issue.
It is best to provide the contnet of your web.config.

**Comment by yanhong2008** [comment]
楼主，解决了吗？我也遇到这个问题了
