### ISSUE TITLE
oap-server 6.6.0版本中链路跟踪不正确

### ISSUE THREAD

**Issue by solapvk** [SkyAPM/SkyAPM-dotnet#273]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

>   SkyApm.Sample.Backend and SkyApm.Sample.Frontend

- What happen?
 调用 Frontend 的 http://localhost:5001/api/values
链路信息如下
![20200110163315](https://user-images.githubusercontent.com/5832358/72138088-fed2f200-33c6-11ea-973d-58af7210cb5c.png)
没有记录Backend的调用信息。
打开日志debug，显示Frontend上报2次Segment，Backend 上报一次。
根据trace_id查看es中存储的Segment信息只有Frontend上报的2次。将Segment转换为json为
`{
  "TraceSegmentId": {
    "IdParts": [
      26,
      10,
      15786398685840002
    ]
  },
  "Spans": [
    {
      "SpanId": 0,
      "ParentSpanId": -1,
      "StartTime": 1578639868584,
      "EndTime": 1578639869900,
      "Refs": [],
      "OperationNameId": 0,
      "OperationName": "/api/values",
      "PeerId": 0,
      "Peer": "::1",
      "SpanType": 0,
      "SpanLayer": 3,
      "ComponentId": 0,
      "Component": "AspNetCore",
      "IsError": false,
      "Tags": [
        {
          "Key": "url",
          "Value": "http://localhost:5001/api/values"
        },
        {
          "Key": "path",
          "Value": "/api/values"
        },
        {
          "Key": "http.method",
          "Value": "GET"
        },
        {
          "Key": "status_code",
          "Value": "200"
        }
      ],
      "Logs": [
        {
          "Time": 1578639868584,
          "Data": [
            {
              "Key": "event",
              "Value": "AspNetCore Hosting BeginRequest"
            },
            {
              "Key": "message",
              "Value": "Request starting HTTP/1.1 GET http://localhost:5001/api/values"
            }
          ]
        },
        {
          "Time": 1578639869900,
          "Data": [
            {
              "Key": "event",
              "Value": "AspNetCore Hosting EndRequest"
            },
            {
              "Key": "message",
              "Value": "Request finished 200 application/json; charset=utf-8"
            }
          ]
        }
      ]
    }
  ],
  "ServiceId": 4,
  "ServiceInstanceId": 26,
  "IsSizeLimited": false
}`
和
`{
  "TraceSegmentId": {
    "IdParts": [
      26,
      10,
      15786398691150003
    ]
  },
  "Spans": [
    {
      "SpanId": 0,
      "ParentSpanId": -1,
      "StartTime": 1578639869115,
      "EndTime": 1578639869754,
      "Refs": [
        {
          "RefType": 1,
          "ParentTraceSegmentId": {
            "IdParts": [
              26,
              10,
              15786398685840002
            ]
          },
          "ParentSpanId": 0,
          "ParentServiceInstanceId": 26,
          "NetworkAddress": "/api/values",
          "NetworkAddressId": 0,
          "EntryServiceInstanceId": 26,
          "EntryEndpoint": "/api/values",
          "EntryEndpointId": 0,
          "ParentEndpoint": "/api/values",
          "ParentEndpointId": 0
        }
      ],
      "OperationNameId": 0,
      "OperationName": "http://localhost:5002/api/values",
      "PeerId": 0,
      "Peer": "localhost:5002",
      "SpanType": 1,
      "SpanLayer": 3,
      "ComponentId": 0,
      "Component": "HttpClient",
      "IsError": false,
      "Tags": [
        {
          "Key": "url",
          "Value": "http://localhost:5002/api/values"
        },
        {
          "Key": "http.method",
          "Value": "GET"
        },
        {
          "Key": "status_code",
          "Value": "200"
        }
      ],
      "Logs": []
    }
  ],
  "ServiceId": 4,
  "ServiceInstanceId": 26,
  "IsSizeLimited": false
}`
使用java 调用http://localhost:5002/api/values 跟踪链路是正确的，上报segment信息2条，其中一条如下：
`{
  "TraceSegmentId": {
    "IdParts": [
      25,
      68,
      15786398778420000
    ]
  },
  "Spans": [
    {
      "SpanId": 1,
      "ParentSpanId": 0,
      "StartTime": 1578639877849,
      "EndTime": 1578639877900,
      "Refs": [],
      "OperationNameId": 0,
      "OperationName": "/api/values",
      "PeerId": 0,
      "Peer": "localhost:5002",
      "SpanType": 1,
      "SpanLayer": 3,
      "ComponentId": 2,
      "Component": "",
      "IsError": false,
      "Tags": [
        {
          "Key": "url",
          "Value": "http://localhost:5002/api/values"
        },
        {
          "Key": "http.method",
          "Value": "GET"
        }
      ],
      "Logs": []
    },
    {
      "SpanId": 0,
      "ParentSpanId": -1,
      "StartTime": 1578639877842,
      "EndTime": 1578639877906,
      "Refs": [],
      "OperationNameId": 0,
      "OperationName": "/values",
      "PeerId": 0,
      "Peer": "",
      "SpanType": 0,
      "SpanLayer": 3,
      "ComponentId": 14,
      "Component": "",
      "IsError": false,
      "Tags": [
        {
          "Key": "url",
          "Value": "http://localhost:8089/values"
        },
        {
          "Key": "http.method",
          "Value": "GET"
        }
      ],
      "Logs": []
    }
  ],
  "ServiceId": 5,
  "ServiceInstanceId": 25,
  "IsSizeLimited": false
}`

**Comment by ElderJames** [comment]
@wu-sheng  Are there any changes after oap-server 6.2?

**Comment by wu-sheng** [comment]
Yes. The storage implementation had been factored in 6.2. After that, es should be initialized again, and new bulk parameters required. Please read storage doc foe the new releases.
Some part of data could be lost if the parameter is not right.
