### ISSUE TITLE
请教一下应如何确保安全性？

### ISSUE THREAD

**Issue by h82258652** [SkyAPM/SkyAPM-dotnet#277]
抱歉，英语不太好就不用英语了。

SkyWalking 版本：6.6.0
SkyAPM.Agent.AspNetCore 版本：0.9.0

目前有两台服务器，一台是应用服务器，另一台是部署了 SkyWalking 的服务器，两台服务器不在一个网段，没法通过内网访问。目前只能 SkyWalking 的服务器开放 11800 端口到公网给应用服务器来使用。但是这样感觉不安全，请问一下有类似 APP ID 这种手段来进行限制吗？

**Comment by wu-sheng** [comment]
Use TLS

**Comment by h82258652** [comment]
Thanks for the response.
https://skyapm.github.io/document-cn-translation-of-skywalking/zh/5.0.0-beta/TLS-CN.html
I will have a try with the document.

**Comment by wu-sheng** [comment]
TLS is not available for backend 6.x and 7.x. As no one added it back after 5.x. If you want to this, set up a proxy before OAP cluster, it should be easy to support TLS without SkyWalking's code change.

**Comment by h82258652** [comment]
@wu-sheng Thank you very much! I will have a try.
