### ISSUE TITLE
.net 怎么配置Authentication呢

### ISSUE THREAD

**Issue by ihenjoy** [SkyAPM/SkyAPM-dotnet#282]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- net 怎么配置Authentication呢？

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Add the `Authentication` option at gRPC section. 
See PR #219 .

```
"gRPC": {
        "Servers": "localhost:11800",
        "Timeout": 100000,
        "ConnectTimeout": 100000,
        "ReportTimeout": 600000,
        "Authentication": ""
      }
```
