### ISSUE TITLE
i think APM got some wrong data of cpu and heap memory 

### ISSUE THREAD

**Issue by jol5** [SkyAPM/SkyAPM-dotnet#286]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking 0.9.0 ， window server 2016/ win10  netcore2.2
- Which company or project?

- What happen?
i got wrong cpu，heap data；like follow
![image](https://user-images.githubusercontent.com/28615922/76192068-d70fd700-621b-11ea-9451-1ea697fbfb4d.png)

If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by snakorse** [comment]
the cpu usage and clr threads have beed fixed, the gc and memoryheap looks well using skyapm with version 1.2.0. I gona close this issue, feel free to reopen or submit new issure if you still have problems playing with the latest version.
