### ISSUE TITLE
Add dotnet module support to SkyWalking e2e test

### ISSUE THREAD

**Issue by ElderJames** [SkyAPM/SkyAPM-dotnet#288]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Add dotnet module support to SkyWalking e2e test

**Comment by feiyun0112** [comment]
@ElderJames 

Can you talk about the current progress?
