### ISSUE TITLE
How to set the environment variable of skyapm agent in the dockerfile of Linux image, using NETCORE 3.1

### ISSUE THREAD

**Issue by huiali** [SkyAPM/SkyAPM-dotnet#290]
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

# Question
How to set the environment variable of skyapm agent in the dockerfile of Linux image, using NETCORE 3.1 ,CentOS 7+

`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base`
`RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf`

`WORKDIR /app`
`EXPOSE 80`
`EXPOSE 443`

`FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build`
`WORKDIR /src`

`COPY . .`
`RUN dotnet build "API.csproj" -c Release -o /app/build`

`FROM build AS publish`
`RUN dotnet publish "API.csproj" -c Release -o /app/publish`

`FROM base AS final`
`WORKDIR /app`
`COPY --from=publish /app/publish .`
`ENTRYPOINT ["dotnet", "API.dll"]`

**Comment by ElderJames** [comment]
Just add  the environment variable above entrypoint:
```
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES SkyAPM.Agent.AspNetCore
ENV SKYWALKING__SERVICENAME sample_app
```

Thanks for contacting us.
