### ISSUE TITLE
 .netcore 3.1 环境下怎么进行某些路径的排除呢？

### ISSUE THREAD

**Issue by yun6cc** [SkyAPM/SkyAPM-dotnet#291]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  .netcore 3.1 环境下怎么进行某些路径的排除呢？
  类似 健康检测，日志记录等并不需要通过 skyapm 记录的。

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Not currently supported. But you can implement `IRequestDiagnosticHandler` and `IHostingDiagnosticHandler`.

Thanks for contacting us.
