### ISSUE TITLE
skywalking结合CAP从发布到消费，无法监控全链路

### ISSUE THREAD

**Issue by yang-xiaodong** [SkyAPM/SkyAPM-dotnet#293]
This issue is copied from https://github.com/dotnetcore/CAP/issues/546#issue-601165435 by @LouieGuo

> skywalking结合CAP，从发布到消费，我这边无法监控到全链路，是需要特定配置吗？

**Comment by yang-xiaodong** [comment]
@LouieGuo please show your environment and configuraiton.

**Comment by LouieGuo** [comment]
ok，wait a minute

**Comment by LouieGuo** [comment]
1、DotNetCore.CAP xxxx 是 3.0.3版本的；
2、Skywalking 安装window下 7.0.0版本。地址：http://skywalking.apache.org/downloads/；
3、SkyAPM.Agent.AspNetCore 安装的是0.9.0版本；

环境配置文件：launchSettings.json

{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:62472",
      "sslPort": 44380
    }
  },
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "FuYu.DistributionCenter.Web": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "SkyAPM.Agent.AspNetCore",
        "SKYWALKING__SERVICENAME": "distributioncenter"
      },
      "applicationUrl": "https://localhost:5001"
    }
  }
}
--------------------------------------------------------------
配置文件：skyapm.json  设置为  较新则复制

{
  "SkyWalking": {
    "ServiceName": "distributioncenter",
    "Namespace": "",
    "HeaderVersions": [
      "sw6"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v6",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "localhost:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000
      }
    }
  }
}

-------------------------------------------------------------
代码中配置CAP的内容

public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();
            var hostingEnvironment = context.Services.GetHostingEnvironment();

            context.Services.AddCap(opt =>
            {
                opt.UseMySql(configuration["ConnectionStrings:DistributionCenter"]);
                opt.UseRabbitMQ(rb =>
                {
                    rb.HostName = "172.16.0.76";
                    rb.Port = 5673;
                    rb.UserName = "admin";
                    rb.Password = "admin";
                    rb.VirtualHost = "my_vhost";
                    rb.ExchangeName = "DistributionCenter_Exchange";
                });
                opt.UseDashboard();
            });
        }

**Comment by LouieGuo** [comment]
1，DotNetCore.CAP xxxx是3.0.3版本的；
2，Skywalking安装窗口下7.0.0版本。地址：http://skywalking.apache.org/downloads/ ； 
3，SkyAPM.Agent.AspNetCore安装的是0.9 .0版本；

环境配置文件：launchSettings.json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:62472",
      "sslPort": 44380
    }
  },
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "FuYu.DistributionCenter.Web": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "SkyAPM.Agent.AspNetCore",
        "SKYWALKING__SERVICENAME": "distributioncenter"
      },
      "applicationUrl": "https://localhost:5001"
    }
  }
}
----------------------------------------------------------
配置文件 skyapm.json  设为  如果较新则复制
{
  "SkyWalking": {
    "ServiceName": "distributioncenter",
    "Namespace": "",
    "HeaderVersions": [
      "sw6"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v6",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "localhost:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000
      }
    }
  }
}

---------------------------------------------
CAP配置文件内容
public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();
            var hostingEnvironment = context.Services.GetHostingEnvironment();

            context.Services.AddCap(opt =>
            {
                //opt.UseEntityFramework<DistributionCenterDbContext>();
                opt.UseMySql(configuration["ConnectionStrings:DistributionCenter"]);
                opt.UseRabbitMQ(rb =>
                {
                    rb.HostName = "xxxxx";
                    rb.Port = 5673;
                    rb.UserName = "xxxx";
                    rb.Password = "xxx";
                    rb.VirtualHost = "my_vhost";
                    rb.ExchangeName = "DistributionCenter_Exchange";
                });
                opt.UseDashboard();
            });
        }

**Comment by yang-xiaodong** [comment]
The SkyAPM.Agent.AspNetCore of version 0.9.0 does not include support for CAP 3.0, you need to use the preview version on MyGet.

You can find the feed here:  https://www.myget.org/F/skyapm-dotnet/api/v3/index.json

**Comment by LouieGuo** [comment]
Thank you. 我改一下版本

**Comment by LouieGuo** [comment]
Skyapm.Agent.AspNetCore 改成 myget 的 0.9.0-prerelease-98779874版本，还是没有效果。

**Comment by yang-xiaodong** [comment]
@LouieGuo please show your environment and configuraiton.

**Comment by yang-xiaodong** [comment]
No response, close this issue.

Provide a sample repository if possible for reopen this issue.
