### ISSUE TITLE
8.0， 9.0 版本SegmentV6Helpers.cs通不多编译，报错

### ISSUE THREAD

**Issue by 602170426** [SkyAPM/SkyAPM-dotnet#295]
SegmentV6Helpers.cs通不过编译，报错

SkyApm.Transport.Grpc.Protocol 这个项目是空的，其他项目有对他的应用，报错

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Thanks for contacting us.

Currently, the protocol for the SkyWlking master branch has been modified and there are breack changes. SkyApm-dotent agent will be adapted later. 

If you need to compile this project now, make sure protocol is version `6.6`.

**Comment by snakorse** [comment]
same with #305 .
