### ISSUE TITLE
SkyAPM 0.9.0 枚举Protocol问题

### ISSUE THREAD

**Issue by ark-wu** [SkyAPM/SkyAPM-dotnet#298]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ark-wu** [comment]
关于SkyAPM的Protocol 枚举, 没有指定**namespace**如图，当程序中存在适用到Protocol的枚举时，会发生冲突歧义。
<img width="2040" alt="WeChat7bed945840cae5dfcc6903c9e3f50261" src="https://user-images.githubusercontent.com/66108161/83227923-d4d46d80-a1b7-11ea-8902-c432f32e6f52.png">
<img width="792" alt="WeChat5ed6120b28fa06f4c03f8b85f53cf64b" src="https://user-images.githubusercontent.com/66108161/83228019-0f3e0a80-a1b8-11ea-9e83-4cbde2813ee8.png">

**Comment by snakorse** [comment]
This is a problem of [skywalking data collect protocol v2.0](https://github.com/apache/skywalking-data-collect-protocol), as the v2.0 protocol is archived, and the latest protocol v3.0 have fixed this problem, so I recommand you use `global::` as a work around if you still want to use skyapm v0.9 with skywalking bellow v8.0.
