### ISSUE TITLE
关于订阅模型性能优化的思考

### ISSUE THREAD

**Issue by rilonggithub** [SkyAPM/SkyAPM-dotnet#299]
SkyAPM-dotnet团队，你们好：

首先感谢你们开源了.Net体系的APM框架项目，我仔细阅读了项目的源码，受益非且，同时也为我们团队实现链路组件提供了无形中的帮助和参考。

阅读源码过程感觉是一个升级打怪的体验，一开始对微软官方的类库System.Diagnostics不太了解，比如在何时回调订阅者的OnNext方法？实现机制是什么？因此查阅了System.Diagnostics. DiagnosticListener的源码，花了2天的时间扫除了我的疑惑。

在阅读SkyAPM-dotnet源码的时候，有个疑惑：
TracingDiagnosticProcessorObserver的代码片段如下，

```
public void OnNext(DiagnosticListener listener)
{
            foreach (var diagnosticProcessor in _tracingDiagnosticProcessors.Distinct(x => x.ListenerName))
            {
                if (listener.Name == diagnosticProcessor.ListenerName)
                {
                    Subscribe(listener, diagnosticProcessor);
                    _logger.LogInformation(
                        $"加载监听： [{diagnosticProcessor.ListenerName}].");
                }
            }
        }
        protected virtual void Subscribe(DiagnosticListener listener,
            ITracingDiagnosticProcessor tracingDiagnosticProcessor)
        {
            listener.Subscribe(new TracingDiagnosticObserver(tracingDiagnosticProcessor, _loggerProvider));
        }
}
```

TracingDiagnosticObserver对象的OnNext方法代码如下：
```
public void OnNext(KeyValuePair<string, object> value)
        {
            foreach (var method in _methodCollection)
            {
                try
                {
                    method.Invoke(value.Key, value.Value);
                }
                catch (Exception exception)
                {
                    _logger.LogError(exception, "执行监听的方法异常！");
                }
            }
        }
```

在TracingDiagnosticObserver对象的OnNext方法中会获得已订阅组件中的所有事件（这里的事件可能不太准确，也可以理解为是场景）的回调，虽然只会调用有DiagnosticName特性的方法，否则抛异常记录log。假如某个组件中定义了10个事件，但我们仅需要订阅其中的一个事件，目前的方式就会存在90%的无效回调，而且会有9次异常，异常对性能影响比较大。

这里的设计思想不知道是否还考虑了其他什么因素，个人感觉这里有性能的损耗。我们是不是可以在Subscribe(DiagnosticListener listener, ITracingDiagnosticProcessor tracingDiagnosticProcessor)方法带上第二个参数即过滤事件的委托，这样既不会出现无效的回调，也不会抛出异常，从框架上来看更合理更健壮。类似的实现代码如下：

```
protected virtual void Subscribe(DiagnosticListener listener,
            ITracingDiagnosticProcessor tracingDiagnosticProcessor)
        {
            var _methods = new List<string>() ;
            foreach (var method in tracingDiagnosticProcessor.GetType().GetMethods())
            {
                var diagnosticName = method.GetCustomAttribute<DiagnosticName>();
                if (diagnosticName == null)
                    continue;
                _methods.Add(diagnosticName.Name);
            }
            listener.Subscribe(new TracingDiagnosticObserver(tracingDiagnosticProcessor, _loggerProvider)
                ,s=> _methods.Contains(s));
        }
```
因为在System.Diagnostics. DiagnosticListener的内部维护了一个订阅者的链表，每次调用Write的时候都会遍历链表上的订阅者并调用OnNext方法，在这里就可以通过IsEnabled委托来过滤。

这是我个人的不成熟的一些想法，请团队大神指点；同时也希望能贡献自己的一点微薄力量。

**Comment by snakorse** [comment]
1. ITracingDiagnosticProcessor 没有订阅某些方法时，执行method.Invoke()并不会抛异常，因为Invoke内部会判断是否与订阅的diagnosticname匹配，不匹配则会退出调用；
2. 通过IsEnable入参，告知listener是否需要write的提议，确实必要，有利于减少不必要的函数调用，提高性能。
