### ISSUE TITLE
Asp.Net 报错

### ISSUE THREAD

**Issue by noobwu** [SkyAPM/SkyAPM-dotnet#300]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
OS:Windows
.NET Runtime:
![image](https://user-images.githubusercontent.com/4328356/83540517-0ab48180-a52b-11ea-9ca9-ffe072666b06.png)

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
![image](https://user-images.githubusercontent.com/4328356/83540429-e658a500-a52a-11ea-909c-95b8fe2d2995.png)

- Please describe about your requirements or improvement suggestions.

**Comment by KevinWG** [comment]
I have met the same question.  when I tried importing it in a .net framework project (asp.net webform), my peoject couldn't run normally.  Same Exception!

Dev : Visual Studio 2019
Ver： .Net Framework 4.6.1
Project:   Asp.Net (WebForm)

mybe there is a dependence libray wrong.    hope it be fixed !
