### ISSUE TITLE
ASP.Net Core3.1版本中报错及解决方案

### ISSUE THREAD

**Issue by rilonggithub** [SkyAPM/SkyAPM-dotnet#301]
最新版本发现在ASP.Net Core3.1版本中报错，我阅读了微软官方.NetCore 团队的源码和提交记录，终于在MvcCoreDiagnosticListenerExtensions.cs 文件中找到了2.1和3.1之间的差别（PS：看得出2.1到3.0版本是做了很多规范性的东西，但也给它的生态系统不兼容，不太友好）。

Bug分析：
在2.1版本中，微软在Microsoft.AspNetCore.Mvc.BeforeAction诊断事件中写入诊断模型的时候，使用的匿名类型，导致参数解析出来就是小写的名称，详见下图：
![image](https://user-images.githubusercontent.com/1730501/84132212-2f06e580-aa78-11ea-807e-ea1679af2f9e.png)

但是在3.1版本中进行了规范，使用了命名类型BeforeActionEventData，而且是分2次提交的代码，所以解析的时候是如下类型：
![image](https://user-images.githubusercontent.com/1730501/84132841-f0255f80-aa78-11ea-9f79-eeea2eb64624.png)

提交的记录如下图：
![image](https://user-images.githubusercontent.com/1730501/84132897-00d5d580-aa79-11ea-879d-efc62bb20e0a.png)

BUG解决：
目前的解决方案是在PropertyAttribute类型中解析参数的时候，发现小写的参数解析出来为null的时候，再将参数名称的首字母大写在解析一次，这种方式为临时解决方案，改动也最少，肯定有更优雅的方式。
![image](https://user-images.githubusercontent.com/1730501/84133305-95403800-aa79-11ea-86a7-ae89cd23680c.png)

如果有遇到类似问题的朋友一起交流。

**Comment by zeaposs** [comment]
Great description of the bug. I've came across this error today. I will post a PR with a temporary fix that is a bit more suitable, but it will render Agent useless for 2.x .Net Core versions. I should be able to make a better version at the end of January.

**Comment by zeaposs** [comment]
I'm not sure, if this bug is replicable in the current code base, as MVC actions aren't tracked anymore:
https://github.com/SkyAPM/SkyAPM-dotnet/blob/6e4ff6b219a1853a5bbe9c6e58e11262b15e5851/src/SkyApm.Diagnostics.AspNetCore/HostingDiagnosticProcessor.cs#L93
Can you confirm this?

**Comment by feiyun0112** [comment]
@rilonggithub 

can you close this issue?

**This project currently supports apps targeting netcoreapp3.1、net5.0、net6.0 or higher.**
