### ISSUE TITLE
The SkyApm.Transport.Grpc project can't not compile.  

### ISSUE THREAD

**Issue by jbjianbin** [SkyAPM/SkyAPM-dotnet#302]
The SkyApm.Transport.Grpc project can't not compile.  

![831AA4C7-3AFE-4800-BD78-EBE44AB35CBB](https://user-images.githubusercontent.com/18735238/84489312-1430ad00-acd4-11ea-9f62-829acf9c4aa0.png)

**Comment by snakorse** [comment]
This is because the `protocol ` folder is a submodule, try following cmd at the repository root folder:
`git submodule init`
`git submodule update`
