### ISSUE TITLE
using SkyWalking.NetworkProtocol not find 

### ISSUE THREAD

**Issue by IAngryBirds** [SkyAPM/SkyAPM-dotnet#305]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

using SkyWalking.NetworkProtocol not find 
(SkyApm.Transport.Grpc  ---->Common ---->  SegmentV6Helper.cs   )

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

the default master version 
in the  .net Runtime 

- What happen?
 
(我下载了默认的master分支，发现代码无法编译通过，在SkyApm.Transport.Grpc  ---->Common ---->  SegmentV6Helper.cs 中有个using SkyWalking.NetworkProtocol 无法被找到 )
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by huohuli008** [comment]
一样的问题，是否有解决方案？

**Comment by snakorse** [comment]
This is because the `protocol` folder is a submodule, try following cmd at the repository root folder:
`git submodule init`
`git submodule update`
