### ISSUE TITLE
SkyApm.Transport.Grpc.V6.ServiceRegister : Register service fail. Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")

### ISSUE THREAD

**Issue by yingpanwang** [SkyAPM/SkyAPM-dotnet#306]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

使用SkyAPM.AspNetCore时注册当前项目失败，查看logs下的日志显示 "Method not found: Register/doServiceRegister"

![image](https://user-images.githubusercontent.com/49632937/85365707-7bfab980-b558-11ea-8341-60886d916ed1.png)

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
通过什么方式可以避免出现这个问题

**Comment by jerrytang67** [comment]
same error +1

**Comment by jerrytang67** [comment]
@yingpanwang to fix this issue is just use aop version 7  but not 8. doServiceRegister is already not in 8.x

**Comment by yingpanwang** [comment]
@jerrytang67 
which aop ?

**Comment by yingpanwang** [comment]
@jerrytang67  OK，it works..

**Comment by NiuziyuanPy** [comment]
你好 问题解决了嘛，我也遇到了

**Comment by jerrytang67** [comment]
解决了,看上面

**Comment by jerrytang67** [comment]
> 你好 问题解决了嘛，我也遇到了

to fix this issue is just use aop version 7 but not 8. doServiceRegister is already not in 8.x

**Comment by snakorse** [comment]
@csm19910701  Use skyapmV1.3.0, and skywalking server version should be v8.x. If you are also using the skyapm.json as config file, delete it and regenerate using the cliw cmd tool

**Comment by cf1998** [comment]
great
