### ISSUE TITLE
配置文件里的Services能配置多个地址吗？怎么配置

### ISSUE THREAD

**Issue by ClementeGao** [SkyAPM/SkyAPM-dotnet#307]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by snakorse** [comment]
You can config multi server addresses split by `,`, e.g. `localhost:11800,localhost:11810`
