### ISSUE TITLE
[Error] SkyApm.Transport.Grpc.V6.ServiceRegister : Register service fail

### ISSUE THREAD

**Issue by LouieGuo** [SkyAPM/SkyAPM-dotnet#308]
[Error] SkyApm.Transport.Grpc.V6.ServiceRegister : Register service fail.
Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")
skywalking:8.0.1
SkyAPM.Agent.AspNetCore:0.9 
请问是目前8.0是没有Register/doServiceRegister的方法是吧 ？7.0是可以了

**Comment by bluexray** [comment]
8.1 也有这个问题，找了一圈没找到问题在哪

**Comment by wu-sheng** [comment]
目前不支持8+的协议。
