### ISSUE TITLE
ASP.NET FRAMEWORK无法收集到日志

### ISSUE THREAD

**Issue by JiaZhenLin** [SkyAPM/SkyAPM-dotnet#309]
与 #202 同样的问题，使用demo中的SkyApm.Sample.AspNet无法收集到日志（另外两个.net core的可正常运行）

**Comment by wei-king** [comment]
我也一样，期待更新

**Comment by wei-king** [comment]
你的问题最后怎么解决的？

**Comment by sw1136562366** [comment]
请问netframework可以正常采集数据吗？net472 NuGet安装SkyAPM.Agent.AspNetCore1.1.0， 添加了skyapm.json ，没有log，也没有数据上报
