### ISSUE TITLE
When will you be able to support .net 5

### ISSUE THREAD

**Issue by dreamMoli** [SkyAPM/SkyAPM-dotnet#310]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
**- when I use the command "dotnet skyapm config", tips: The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.I didn't install it. So I want to know when will you be able to support .net 5.**

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ElderJames** [comment]
Thank you for contacting us @dreamMoli .
We will support .NET 5 after it GA release.
You can fork a piece of code first to make changes, and you're welcome to contribute it to the main branch.

**Comment by dreamMoli** [comment]
ok i got it, thanks
