### ISSUE TITLE
Method not found: Register/doServiceRegister

### ISSUE THREAD

**Issue by dreamMoli** [SkyAPM/SkyAPM-dotnet#311]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
**How to solve this error.**
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
**apache/skywalking-oap-server:8.0.1-es7
apache/skywalking-ui:8.0.1

OS MAC OS 14.04

.NET RUNTIME:.NET 5 PREVIEW 7**

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
**2020-07-30 13:35:51.890 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.V6.ServiceRegister : Register service fail.
Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")
   at SkyApm.Transport.Grpc.V6.ServiceRegister.<>c__DisplayClass9_0.<<RegisterServiceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at SkyApm.Transport.Grpc.Common.Call.Execute[T](Func`1 task, Func`1 errCallback, Func`1 errMessage)
2020-07-30 13:35:51.890 +08:00 [sample_app] [Warning] SkyApm.Transport.Grpc.ConnectionManager : Connection state changed. Connected -> Ready . Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")**
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
dotnet agent doesn't support 8+ yet

**Comment by dreamMoli** [comment]
When will it be supported ?

**Comment by wu-sheng** [comment]
I don't know. The different agent has different team working on it.

**Comment by dreamMoli** [comment]
.....

**Comment by snakorse** [comment]
now skywalking 8.x is supported.
