### ISSUE TITLE
从配置中心读取SkyWalking配置会被默认配置覆盖

### ISSUE THREAD

**Issue by AlphaYu** [SkyAPM/SkyAPM-dotnet#312]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [-] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
version 0.90, Linux，.net core 3.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
从配置中心读取SkyWalking配置会被默认配置覆盖
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
开发环境中，我将skyamp的配置放在skyapm.json文件中或者放在appsettings.xxx.json文件中都可以正常运行。
然而生产环境中，我项目的appsettings.json的配置内容是放在consul配置中心的，同时appsettings.json也包含了skyapm的配置。项目在Program.CreateHostBuilder()方法中将会将appsettings.json读取到Configuration对象，这里是没有问题的，我调试到已经读取到skyapm所有配置信息。但是却被默认配置覆盖了。
我看了/src/SkyApm.Utilities.Configuration/ConfigurationFactory.cs 与 /src/SkyApm.Utilities.Configuration/ConfigurationBuilderExtensions.cs 这两个文件的源码，我想应该是skyamp只会加载appsettings.json与skyamp.json的内容，如果这两个文件没有配置，就不会覆盖默认配置，没有去处理其他配置源的问题。

**Comment by foreverhot1019** [comment]
环境变量的原因

**Comment by AlphaYu** [comment]
> 环境变量的原因

不是的，没有关系的。。生产环境，放在配置文件里是可以读取到的，我的问题是配置放在consul配置中心。

**Comment by itsvse** [comment]
解决方案：

https://github.com/SkyAPM/SkyAPM-dotnet/pull/341/commits/f2770c34e922dffec1664eb2805b1798eaecb78d
https://www.itsvse.com/thread-9468-1-1.html

**Comment by AlphaYu** [comment]
@itsvse 谢谢，我好好研究下。再来汇报。

**Comment by snakorse** [comment]
Fixed by pr #341 .
