### ISSUE TITLE
在skywalking UI界面无法看到链路调用错误的堆栈信息

### ISSUE THREAD

**Issue by LouieGuo** [SkyAPM/SkyAPM-dotnet#318]
在skywalking UI界面无法看到链路调用错误的堆栈信息
环境：
asp.net core 3.1
SkyAPM.Agent.AspNetCore 0.9.0-prerelease-98779874 (来自：https://www.myget.org/F/skyapm-dotnet/api/v3/index.json)

请问：还需要添加什么nuget包吗？还是哪里没有配置清楚？

**Comment by LouieGuo** [comment]
![image](https://user-images.githubusercontent.com/29138525/90466011-3ebf3c00-e143-11ea-9aa7-aea9265a4906.png)

**Comment by Weidaicheng** [comment]
I got the same, please tell if anyone who knows how to solve, thx.

**Comment by foreverhot1019** [comment]
在其他节点也需要安装SkyApm.Agenet.AspNetCore包的，及配置的。

**Comment by huohuli008** [comment]
有没有试过 **SkyAPM.Agent.AspNetCore 1.0.0**版本？
我们也没查看到堆栈信息，正在尝试1.0.0

**Comment by foreverhot1019** [comment]
> 有没有试过 **SkyAPM.Agent.AspNetCore 1.0.0**版本？
> 我们也没查看到堆栈信息，正在尝试1.0.0

我用的是0.9.0版本，差别应该不大

**Comment by hylun001** [comment]
我也有这个问题

**Comment by hylun001** [comment]
public void EndRequest(SegmentContext segmentContext, HttpContext httpContext)
        {
            var statusCode = httpContext.Response.StatusCode;
            if (statusCode >= 400)
            {
                segmentContext.Span.ErrorOccurred();
            }

            
            segmentContext.Span.AddTag(Tags.STATUS_CODE, statusCode);
            segmentContext.Span.AddLog(
                LogEvent.Event("AspNetCore Hosting EndRequest"),
                LogEvent.Message(
                    $"Request finished {httpContext.Response.StatusCode} {httpContext.Response.ContentType}"));
        }

**Comment by hylun001** [comment]
```
 public void EndRequest(SegmentContext segmentContext, HttpContext httpContext)
        {
            var statusCode = httpContext.Response.StatusCode;
            if (statusCode >= 400)
            {
                segmentContext.Span.ErrorOccurred();
            }

            
            segmentContext.Span.AddTag(Tags.STATUS_CODE, statusCode);
            segmentContext.Span.AddLog(
                LogEvent.Event("AspNetCore Hosting EndRequest"),
                LogEvent.Message(
                    $"Request finished {httpContext.Response.StatusCode} {httpContext.Response.ContentType}"));
        }
```

**Comment by snakorse** [comment]
只有未捕获的异常才会记录下堆栈信息

**Comment by hylun001** [comment]
问题是我特意throw出异常，都没有捕获哦

**Comment by snakorse** [comment]
我用skyapm 1.0.0 + skywalking oapserver 8.1.0，测试是可以看到未捕获的异常的stack信息的，建议可以尝试升级下试试

**Comment by snakorse** [comment]
@hylun001 问题有解决吗？有没有尝试升级到最新版试试？

**Comment by snakorse** [comment]
@hylun001 这个issue我先关了，如果还有问题可以重新打开或提新的issue
