### ISSUE TITLE
How to Config the  environment variable with framework 4.6.1

### ISSUE THREAD

**Issue by wei-king** [SkyAPM/SkyAPM-dotnet#319]
Asp.NetCore is run well,but framework4.6.1 is not, Do also need to configure environment variables?

**Comment by foreverhot1019** [comment]
需要手动设置 环境变量，或者 使用winapi设置，不能像.NetCore一样直接Environment.SetEnvironmentVariable("TEST1", "MyTest", EnvironmentVariableTarget.Machine);

**Comment by snakorse** [comment]
@wei-king Do you mean the `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` environment variable? For framework 4.6.1, this is not necessary, the asp.net use an similar but different way, it use the `PreApplicationStartMethod` attribute to inject the tracing fuctions to `Request Pipeline`, so normally you reference the `SkyApm.Agent.AspNet` nuget package and all are done.

**Comment by snakorse** [comment]
I will close this, feel free to create a new issue if you still have problems working with framework 4.6.1.
