### ISSUE TITLE
为啥要设置SpanId和ParentSpanId 为固定值

### ISSUE THREAD

**Issue by felixwan-git** [SkyAPM/SkyAPM-dotnet#322]
我们服务的调用链是：　user -> api -> grpc service -> db
现在有个问题是追踪不完整，形成了两条调用链　　user - > api    user->grpc service -> db
Json数据查看后TraceId都是一样的，但是查看源码后发现　SpanId 和 ParentSpanId 永远为　０和 -1 
不太清楚这是否是导致服务追踪链条不完整的原因

**Comment by heyanlong** [comment]
spanid 和 parentspanid 是有规范的
你现在的真实请求流程是什么？

**Comment by felixwan-git** [comment]
前端发起Http请求给WebApi然后到Grpc服务读取数据库数据返回。　　
现在追踪被分割成两部分　　　
１、前端到WebApi到Grpc　　
２、Grpc到Db　　
　　
刚才看了Go 的实现，ParentSpanId是等于上一步流程的SpanId，所以觉得会不会是这个问题，因为SpanId和ParentSpanId永远是０和－１

**Comment by heyanlong** [comment]
grpc是独立服务吗？
api是一个服务
grpc又是一个服务？

**Comment by felixwan-git** [comment]
嗯，Api 和Grpc都是独立的服务，刚才查看了es发现是TraceId没有被上传，不是这个SpanId的问题，谢谢，我先关闭Issue了

**Comment by felixwan-git** [comment]
我找到问题了，当设置　SkyWalking:Namespace　为大小写混合的时候，由于Header会将key变成小写，此时会导致无法匹配到Formater,　下游程序就会创建一个空的Carrier，TraceId也就改变了
![深度截图_选择区域_20200826191815](https://user-images.githubusercontent.com/45676208/91297856-9740aa00-e7d1-11ea-80dc-dbef24e44df1.png)
这个地方应该改成忽略大小写或者释放出异常没有Key被匹配到

**Comment by wificlub-code** [comment]
出现了与你一样的问题，链路中断，至今也没解决

**Comment by felixwan-git** [comment]
@wificlub-code 你检查下 SkyWalking:Namespace 这个命名空间是不是有大小写，如果有改成全部小写试试，应该就可以了，我之前就是这样解决的，但是目前我们已经打算放弃skywalking了，收集数据太多了，对中小型公司貌似并不合适

**Comment by wificlub-code** [comment]
我没有设置SkyWalking:Namespace，没有设置这个会不会有影响？其他非grpc项目就没这个问题，我们项目环境是.net5.0。请问你们现在用的是什么链路追踪，分享一下

**Comment by felixwan-git** [comment]
现在没用链路追踪了，等过一段时间再调研，现在还没空搞这个

**Comment by wificlub-code** [comment]
> 现在没用链路追踪了，等过一段时间再调研，现在还没空搞这个

我的问题解决了，服务端增加 配置
services.AddGrpc(options =>
            {
                    options.Interceptors.Add<ServerDiagnosticInterceptor>();
            });
客户端增加配置AddInterceptor<ClientDiagnosticInterceptor>();
