### ISSUE TITLE
How to use IEntrySegmentContextAccessor in OnActionExecuted?

### ISSUE THREAD

**Issue by Weidaicheng** [SkyAPM/SkyAPM-dotnet#324]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I was trying to get TraceId and set it into my returning object, it worked fine in controller, but I wanted to write a common method to set TraceId in OnActionExecuted method but the IEntrySegmentContextAccessor.Context was null, how should I use this?

___
### Bug
- I'm using the source code from v8/protocol branch on .net core 3.1

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by snakorse** [comment]
I made a test, but did not reproduce the problem, I got the SegmentContext correctly. Can you show how you write your common method and the way you use in OnActionExecuted method? 
One thing to note, to get the correct context value, you should follow the async await pattern when use in async scenes.

**Comment by snakorse** [comment]
I will go ahead and close this issue, but feel free to reopen it if you have any follow questions.
