### ISSUE TITLE
.net framework下使用autofac如何进行注册

### ISSUE THREAD

**Issue by One-One-Code** [SkyAPM/SkyAPM-dotnet#325]
webapi如何使用autofac如何进行注册
使用出现如下错误：
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SkyApm.InstrumentStartup' can be invoked with the available services and parameters:
Cannot resolve parameter 'SkyApm.Diagnostics.TracingDiagnosticProcessorObserver observer' of constructor 'Void .ctor(SkyApm.Diagnostics.TracingDiagnosticProcessorObserver, System.Collections.Generic.IEnumerable`1[SkyApm.IExecutionService], SkyApm.Logging.ILoggerFactory)'.

**Comment by liuhaoyang** [comment]
暂不支持.NET Framework
