### ISSUE TITLE
虚拟机中安装的skywalking，无法收集项目中的数据。这是为啥？

### ISSUE THREAD

**Issue by yunbaozhou** [SkyAPM/SkyAPM-dotnet#329]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
我在虚拟机中centos7系统安装了skywalking 。都运行起来了。但是就是收集不到服务数据。（服务里面代理啥的都配置了，也都显示连接上skywalking 接口了）

![image](https://user-images.githubusercontent.com/26819003/93230796-a7cdba00-f7aa-11ea-8a35-36e10a39fe70.png)
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

.net core 3.1     skywalking7

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yunbaozhou** [comment]
![image](https://user-images.githubusercontent.com/26819003/93230944-d481d180-f7aa-11ea-9b3b-7bff20205e86.png)

**Comment by yunbaozhou** [comment]
不知道从哪里排查问题？

**Comment by imyounghan** [comment]
首先看你的日志输出你用的agent应该是最新的1.0.0，则安装的skywalking-oap得是8.x版本，查看server端的日志是否有error。
目前我从0.9.0升级到1.0.0，出现汇报到oap端数据写入失败，群里反映过没人响应，.net sdk不受待见

**Comment by imyounghan** [comment]
建议先用0.9.0版本，对应的oap是7.0，目前正常

**Comment by yunbaozhou** [comment]
我改为 0.9.0版本后，还是不行。webapp.log 如下图：
![image](https://user-images.githubusercontent.com/26819003/93580624-9e269b00-f9d2-11ea-8c53-70a797ad21d1.png)

skywalking-oap-server.log如下：
![image](https://user-images.githubusercontent.com/26819003/93580736-c31b0e00-f9d2-11ea-9e23-09691d565be8.png)



未发现异常情况。“查看server端的日志是否有error” 您所说的日志，是上面两个日志吗？

**Comment by yunbaozhou** [comment]
> 首先看你的日志输出你用的agent应该是最新的1.0.0，则安装的skywalking-oap得是8.x版本，查看server端的日志是否有error。
> 目前我从0.9.0升级到1.0.0，出现汇报到oap端数据写入失败，群里反映过没人响应，.net sdk不受待见

确实资料太少了。“查看server端的日志是否有error”  查看的日志是skywalking-oap-server.log吗？

**Comment by yunbaozhou** [comment]
> 建议先用0.9.0版本，对应的oap是7.0，目前正常

感谢指点。已经解决了。我这边的问题出在skyapm.json 中sw的版本配置上。

**Comment by imyounghan** [comment]
> > 建议先用0.9.0版本，对应的oap是7.0，目前正常
> 
> 感谢指点。已经解决了。我这边的问题出在skyapm.json 中sw的版本配置上。

你用的最新的1.0.0版本？

**Comment by yunbaozhou** [comment]
> > > 建议先用0.9.0版本，对应的oap是7.0，目前正常
> > 
> > 
> > 感谢指点。已经解决了。我这边的问题出在skyapm.json 中sw的版本配置上。
> 
> 你用的最新的1.0.0版本？

不是的。是6.6.0 .我自己配置错了。

**Comment by yunbaozhou** [comment]
> > > 建议先用0.9.0版本，对应的oap是7.0，目前正常
> > 
> > 
> > 感谢指点。已经解决了。我这边的问题出在skyapm.json 中sw的版本配置上。
> 
> 你用的最新的1.0.0版本？

你有交流群吗？我申请skywaking 的交流群，没有通过。哎~   有没有微信的交流群啊，没有我们组建一个。如何
