### ISSUE TITLE
发布后的dotnet projectName.dll 启动方式连不上skywalking

### ISSUE THREAD

**Issue by yanhong2008** [SkyAPM/SkyAPM-dotnet#330]
dotnet run可以连上skywalking，，但是发布后的dotnet projectName.dll 启动方式连不上skywalking，请问skywalking不支持发布后的启动吗？

**Comment by snakorse** [comment]
请检查以下两项：
1. 设置了环境变量 ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
2. 发布后的程序目录包含skyapm.json，并检查该文件内容是否正确配置

**Comment by foreverhot1019** [comment]
手动设置环境变量，或者 在 program里写
Environment.SetEnvironmentVariable("ASPNETCORE_HOSTINGSTARTUPASSEMBLIES", "SkyAPM.Agent.AspNetCore");

**Comment by snakorse** [comment]
Since long time no reply, I will go ahead and close this issue, feel free to reopen this if you have any following questions.
