### ISSUE TITLE
有没有微信交流群啊？有的话，拉我一下啊。  没有的话，大家组建一个~  扫码加入.net / .net core skywalking 交流群(15162441842)

### ISSUE THREAD

**Issue by yunbaozhou** [SkyAPM/SkyAPM-dotnet#331]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yunbaozhou** [comment]
![Uploading image.png…]()

**Comment by heyanlong** [comment]
建议在GitHub issues交流吧，这样可以看到处理过程

**Comment by snakorse** [comment]
因该issue无关代码问题，我关闭了，有其他使用问题欢迎继续提issue
