### ISSUE TITLE
没有像java一样的 ignore_suffix和ignore_path 设置选项吗？

### ISSUE THREAD

**Issue by foreverhot1019** [SkyAPM/SkyAPM-dotnet#332]
不可以设置忽略指定path规则和后缀名url

翻了源码的 default 配置也没有找到相关的设置，应该怎么设置

**Comment by dasajia2lang** [comment]
我也想有设置一下忽略某些url的问题，我试了下好像那个apm-trace-ignore-plugin这个东西没用

**Comment by foreverhot1019** [comment]
> 我也想有设置一下忽略某些url的问题，我试了下好像那个apm-trace-ignore-plugin这个东西没用

还是java程序员爽，所有配置都有，.net还得翻源码看，还不一定写了

**Comment by AlphaYu** [comment]
各位都找到了吗，是比较重要喔。比方说consul的健康监测，不停的扫系统，频率还那么高，把skywalking 的 dashbord都占满了。
