### ISSUE TITLE
追踪分页超过666返回错误Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]

### ISSUE THREAD

**Issue by tvrc1990** [SkyAPM/SkyAPM-dotnet#335]
___
### 问题
追踪->端点列表 
列表每页15条数据，显示总页数1000多页，但最大只能到666页，超过666页接口请求就出现以下错误信息
Exception while fetching data (/traces) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]

![image](https://user-images.githubusercontent.com/7088242/96947787-a795ac80-1516-11eb-8b3e-39f6bf2aa28d.png)

___
### 环境
apache-skywalking-apm-8.1.0 单机
elasticsearch 6.8.0 单机
windows server 2012 R2 32G

**Comment by liuhaoyang** [comment]
ES的分页默认只能拉到10000条，如果想看后面的数据，可以跳转ES对应的参数
