### ISSUE TITLE
Asp.Net sample lost tracing span

### ISSUE THREAD

**Issue by snakorse** [SkyAPM/SkyAPM-dotnet#339]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Asp.Net sample lost tracing span. When calling the /api/values endpoint, skywalking ui display the root request as a Broken-VirtualNode, it should display as AspNet component with `/api/values` endpoint.

**Comment by liuhaoyang** [comment]
The design of skyapm-dotent is not suitable for asp.net pipeline, so in the new version, we have removed the support for asp.net
