### ISSUE TITLE
Support the Skywalking Cross Process Correlation Headers Protocol

### ISSUE THREAD

**Issue by snakorse** [SkyAPM/SkyAPM-dotnet#353]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Support the [Skywalking Cross Process Correlation Headers Protocol](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Correlation-Headers-Protocol-v1.md)

**Comment by feiyun0112** [comment]
@snakorse 

Can you talk about the current progress?
