### ISSUE TITLE
无法连接到skyapm.oap

### ISSUE THREAD

**Issue by ligg** [SkyAPM/SkyAPM-dotnet#359]
skywalking server的地址配置成域名无法连接到oap，配置成ip就没问题，在docker-compose里通过容器名去访问也是连接不成功的，这是为什么？

**Comment by noobwu** [comment]
我也是同样的问题，日志有信息，但是oap没数据
![image](https://user-images.githubusercontent.com/4328356/105467865-390cea00-5cd1-11eb-8ac1-2da274a2bd4a.png)
![image](https://user-images.githubusercontent.com/4328356/105467958-52159b00-5cd1-11eb-9673-8d80a1541eb8.png)

**Comment by noobwu** [comment]
好像什么都没有

![image](https://user-images.githubusercontent.com/4328356/105569444-898d5180-5d7c-11eb-82e6-4308f9575f9f.png)

**Comment by noobwu** [comment]
> skywalking server的地址配置成域名无法连接到oap，配置成ip就没问题，在docker-compose里通过容器名去访问也是连接不成功的，这是为什么？
我的docker-compose配置如下
`version: '3.8'
services:
  sw8_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: sw8_elasticsearch
    restart: always
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail sw8_elasticsearch:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  sw8_kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: sw8_kibana
    depends_on:
      - sw8_elasticsearch
    links:
      - sw8_elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://sw8_elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://sw8_elasticsearch:9200 

  sw8_oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    container_name: sw8_oap
    depends_on:
      - sw8_elasticsearch
    links:
      - sw8_elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: sw8_elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
  
  sw8_ui:
    image: apache/skywalking-ui:8.3.0
    container_name: sw8_ui
    depends_on:
      - sw8_oap
    links:
      - sw8_oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: sw8_oap:12800
      TZ: Asia/Shanghai

`
![image](https://user-images.githubusercontent.com/4328356/105573274-4f7d7900-5d97-11eb-87b2-74e7bd8d2a65.png)

![image](https://user-images.githubusercontent.com/4328356/105573281-5f955880-5d97-11eb-859f-51a201b20f6c.png)

**Comment by ligg** [comment]
我的代码和oap在compose里放到同一个虚拟network，然后代码里通过oap的服务名去连接是连不上的，现在我通过宿主机的ip去连接是可以的

**Comment by osqpt** [comment]
只能通过IP嘛
