### ISSUE TITLE
netframework472, SkyAPM.Agent.AspNetCore 1.1.0，no support

### ISSUE THREAD

**Issue by sw1136562366** [SkyAPM/SkyAPM-dotnet#362]
ASP.NET Web(.Net Framework)
1、netframework472
2、NuGet 程序包安装SkyAPM.Agent.AspNetCore 1.1.0
3、dotnet skyapm config sample_app 192.168.0.1:11800

run app, no log, noda data report
need any other configuration？？？

**Comment by liuhaoyang** [comment]
I'm sorry this instrument only supports Asp.Net Core, and we have no plans to support ASP.NET.
