### ISSUE TITLE
skyapm.json中无InstanceUuid配置

### ISSUE THREAD

**Issue by zhuanshujianghai** [SkyAPM/SkyAPM-dotnet#367]
agent.instance_uuid | 实例id。skywalking会将实例id相同的看做一个实例。如果为空，skywalking agent会生成一个32位的uuid。
导致skywalking-ui中会看到很多跟了uuid的实例

**Comment by snakorse** [comment]
你可以通过环境变量或在skyapm.json中指定`Skywalking__ServiceInstanceName`来固定实例名

**Comment by zhuanshujianghai** [comment]
> 你可以通过环境变量或在skyapm.json中指定`Skywalking__ServiceInstanceName`来固定实例名，但请注意，同一个服务的不同实例应该有不同的ServiceInstanceName

不同服务器，可以通过变量来确定实例名吗？比如 {Date}这种变量，有没有类似Ip的变量？这样就不用每台服务器手动改了

**Comment by snakorse** [comment]
抱歉，当前不支持变量的写法，但我觉得变量这个想法值得考虑
