### ISSUE TITLE
The source code cannot be compiled

### ISSUE THREAD

**Issue by GavinHome** [SkyAPM/SkyAPM-dotnet#374]
- Why do you submit this issue?
- Question or discussion

### Question
 
I download version 0.9.0 source file（from https://github.com/SkyAPM/SkyAPM-dotnet/tags), open it with visual studio 2019, and compiled the project, but got 62+ errors. Can you give me a source code that can be compiled successfully?

![image](https://user-images.githubusercontent.com/5460850/105428581-9893d700-5c8a-11eb-85de-0c0007941254.png)

![image](https://user-images.githubusercontent.com/5460850/105429576-a5b1c580-5c8c-11eb-8023-eb864b0c6e55.png)

[SkyAPM-dotnet-0.9.0.zip](https://github.com/SkyAPM/SkyAPM-dotnet/files/5852847/SkyAPM-dotnet-0.9.0.zip)

**Comment by liuhaoyang** [comment]
We use submodule to add skywalking data protocol file to the project, I found that the source code downloaded from release does not contain submodule.
Then you can clone the project through git, checkout to v0.9 tag, update the submodule, and then the project can be compiled correctly.

**Comment by wu-sheng** [comment]
Please use this page to download. Use GitHub clone instead.

**Comment by GavinHome** [comment]
> We use submodule to add skywalking data protocol file to the project, I found that the source code downloaded from release does not contain submodule.
> Then you can clone the project through git, checkout to v0.9 tag, update the submodule, and then the project can be compiled correctly.

Thank you very much.
