### ISSUE TITLE
Invite Michał Kostrzewski as a maintainer of dotnet agent.

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/SkyAPM-dotnet#376]
Hi Michał(@zeaposs)

I noticed you have been taking care of the questions and issues. I want to check with your, whether do you have interest to join dotnet-team of SkyAPM org  as a maintainer.

cc @dotnet-team

**Comment by zeaposs** [comment]
Hi,
I'm interested and I'll happily help you with SkyAPM for dotnet.

**Comment by wu-sheng** [comment]
Could you join the Apache slack, and join the skywalking channel?

**Comment by zeaposs** [comment]
Done.
