### ISSUE TITLE
can i set collecting request body and header？

### ISSUE THREAD

**Issue by GavinHome** [SkyAPM/SkyAPM-dotnet#377]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?

Does dotnet-agent support collecting request body and request header information?

**Comment by zeaposs** [comment]
No, dotnet-agent doesn't support it yet.
@wu-sheng how do you want this to be implemented? The same way as in [Java agent](https://github.com/apache/skywalking/blob/8c51043dbfc12b283a523d3dcd9e03023dfdd1a6/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-commons/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/commons/interceptor/AbstractMethodInterceptor.java#L221) ?

**Comment by wu-sheng** [comment]
I think Java agent supports header and key-value parameters(get/post) only. Fetching the body in Java APIS could cause the HTTP request stream unreadable by the framework or user codes.
At the same time, these should be optional considering the performance.

**Comment by snakorse** [comment]
Feature implemented, will be included in the next release v1.3.0. Before the release, you can try the latest preview packages from MyGet source.
