### ISSUE TITLE
请支持Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by wificlub-code** [SkyAPM/SkyAPM-dotnet#378]
请把System.Data.SqlClient替换为Microsoft.Data.SqlClient，因为System.Data.SqlClient已经过时了

**Comment by doufeng007** [comment]
+10086

**Comment by brommz** [comment]
Up

**Comment by ElderJames** [comment]
FYI https://github.com/dotnet/SqlClient/pull/515

**Comment by snakorse** [comment]
Fixed by #387
