### ISSUE TITLE
How to set up and collect mongodb information on v1.2.0

### ISSUE THREAD

**Issue by GavinHome** [SkyAPM/SkyAPM-dotnet#382]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
How to set up and collect mongodb information on v1.2.0？

**Comment by snakorse** [comment]
Please refer to the doc [here](https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/src/SkyApm.Diagnostics.MongoDB)
