### ISSUE TITLE
should replace existing header when inject http headers

### ISSUE THREAD

**Issue by zpf1989** [SkyAPM/SkyAPM-dotnet#383]
1. SkyAPM-dotnet 1.2.0
2. aspnetcore 3.1
3. when send http request through a gateway,the call chain is break.
here is the header got in the service behind gateway:
`sw8:1-NTUzNWZiNGU1ZmU1YmU4OWQwOTdlZTgwNDYyZGIwYTguNjUuMTYxMjQ4Nzg1MjMwMzAwMDE=-NTUzNWZiNGU1ZmU1YmU4OWQwOTdlZTgwNDYyZGIwYTguNjUuMTYxMjQ4Nzg1MjMwNjAwMDM=-0-RW5qb3lUZXN0-MTkyLjE2OC41Ni4xQGVlZWRiNTU2ODgyYjQ1OGJhM2M0ZmEzOTdkOTcxZjBm-aHR0cDovLzE5Mi4xNjguNTYuMjAwOjc4ODAvaWRzYXBpL2VqdHJhY2U=-MTkyLjE2OC41Ni4yMDA6Nzg4MA==, 1-NTUzNWZiNGU1ZmU1YmU4OWQwOTdlZTgwNDYyZGIwYTguNjUuMTYxMjQ4Nzg1MjMwMzAwMDE=-YTc3YjdkNzRlYmE5MjU0ZTAyYmYwMTEwZjQzZmU1NTQuMTUyLjE2MTI0ODc4NTI1MzAwMDI4-0-R2F0ZXdheQ==-MTEwLjExMC4wLjRAMmI5YWQ4OTNkOTc3NDQwN2IyMTcwMTcwM2RhZGY3Zjc=-aHR0cDovLzE5Mi4xNjguNTYuMjAwOjg4ODgvZWp0cmFjZQ==-MTkyLjE2OC41Ni4yMDA6ODg4OA==`,
as you can see,it has 2 whole sw8 carriers:
-- one because of the gateway passing through the headers from client
-- the other one comes from the current carrier injected before sending a http request
4. when decode the header,it throw exception for bad base64format(using the split char '-'),and the chain breaks finally.
5. so i think it's better to overrite the sw header if it is existing when inject,thanks !

**Comment by wu-sheng** [comment]
Yes, gateway should override the header. Submit a pull request please.
