### ISSUE TITLE
有没有这个探针设计的思想与架构图给我们分享下呢？

### ISSUE THREAD

**Issue by taomylife521** [SkyAPM/SkyAPM-dotnet#388]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by snakorse** [comment]
简单来说，没有，skyapm背后的思想还是比较容易理解的，主要是基于`DiagnosticSource`机制来实现对特定组件的观测，你可以下载源码稍微探索调试下，应该不难理解。
以对httpclient的诊断流程示例，大概其画了个草图：
![image](https://user-images.githubusercontent.com/11673037/111959258-2d9b3b00-8b29-11eb-844d-c1c099577aa5.png)

**Comment by liuhaoyang** [comment]
> 暂时没有，skyapm背后的思想还是比较容易理解的，主要是基于`DiagnosticSource`机制来实现对特定组件的观测，你可以下载源码稍微探索调试下，应该不难理解。
> 以对httpclient的诊断流程示例，大概其画了个草图：
> ![image](https://user-images.githubusercontent.com/11673037/111959258-2d9b3b00-8b29-11eb-844d-c1c099577aa5.png)

Can you help submit a design document?

**Comment by snakorse** [comment]
@liuhaoyang ok, I will work on it.
