### ISSUE TITLE
git clone下来代码编译不通过

### ISSUE THREAD

**Issue by taomylife521** [SkyAPM/SkyAPM-dotnet#389]
![image](https://user-images.githubusercontent.com/9649318/110566125-89111480-818a-11eb-90bc-93ac432476f2.png)

**Comment by snakorse** [comment]
run `git submodule init & update`

**Comment by taomylife521** [comment]
![image](https://user-images.githubusercontent.com/9649318/110566932-abeff880-818b-11eb-85e3-6c6019988c64.png)
更新了还是报错！

**Comment by snakorse** [comment]
looks like you just run the `git submodule init`,
you should then run `git submodule update`

**Comment by taomylife521** [comment]
![image](https://user-images.githubusercontent.com/9649318/110567142-012c0a00-818c-11eb-80e3-5561ecc6f09e.png)

**Comment by snakorse** [comment]
timeout connecting github, try later or  using a proxy

**Comment by cnlangzi** [comment]
@taomylife521  I had the same problem. please check your nuget packages.  Grpc.Tools may be not installed correctly.
