### ISSUE TITLE
the project SkyApm.Transport.Grpc failed to compile because lack reference of SkyWalking.NetworkProtocol.V8

### ISSUE THREAD

**Issue by yuchengit** [SkyAPM/SkyAPM-dotnet#392]
I have encountered the issue  as the title says ，and i can't find the related package on the public nuget source，how to solve it?

**Comment by snakorse** [comment]
Maybe you should run the git submodule commands before build. see the doc [there ](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/docs/guides/how-to-build.md)

**Comment by snakorse** [comment]
I'm gona close this, but feel free to reopen it if you have any further questions.

**Comment by yuchengit** [comment]
I downloaded the zip package directly before，i try to clone the code by git client，have solved it，thank you very much!
