### ISSUE TITLE
上报的sample泛型主机追踪数据没显示

### ISSUE THREAD

**Issue by taomylife521** [SkyAPM/SkyAPM-dotnet#395]
![image](https://user-images.githubusercontent.com/9649318/111606432-2961db80-8812-11eb-9a46-a139a7005528.png)
![image](https://user-images.githubusercontent.com/9649318/111606571-54e4c600-8812-11eb-8413-31127d41308c.png)
![image](https://user-images.githubusercontent.com/9649318/111606613-64fca580-8812-11eb-97d8-962fb9d5c144.png)

日志里面显示上传数据已经成功！但是web端追踪数据没显示啊

**Comment by snakorse** [comment]
检查skywalking UI上 时间区间筛选是否正确

**Comment by snakorse** [comment]
先关闭该issue了，有问题可以reopen
