### ISSUE TITLE
Throw exception when using in Abp Vnext

### ISSUE THREAD

**Issue by gainorloss** [SkyAPM/SkyAPM-dotnet#396]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

> System.TypeInitializationException:“The type initializer for 'Microsoft.Data.SqlClient.SqlConnection' threw an exception.”
> FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。
> ![image](https://user-images.githubusercontent.com/26458238/111722104-23b0d800-889c-11eb-92bd-89dcaf6987d6.png)

SkyAPM.Agent.AspNetCore:1.2.0
Abp Vnext:4.2.1

**Comment by gainorloss** [comment]
After i install the package named System.Data.SqlClient(4.6.1),it did not work as before.

**Comment by snakorse** [comment]
You should install System.Data.SqlClient(4.8.2), refer this issue #304

**Comment by snakorse** [comment]
gona close this. feel free to reopen it if you have any further problems.
