### ISSUE TITLE
coreclr_profiler 这个分支目前处于什么状态呢？可以用于生产环境吗？

### ISSUE THREAD

**Issue by taomylife521** [SkyAPM/SkyAPM-dotnet#397]
![image](https://user-images.githubusercontent.com/9649318/111768368-d146da00-88e2-11eb-9aba-526f330031b9.png)
这个环境变量就是指的这个c++类库生成的dll吗？c++类库生成报找不到头文件，是依赖的啥库或者sdk没安装吗？
![image](https://user-images.githubusercontent.com/9649318/111768577-10752b00-88e3-11eb-83e4-7a4de1e564c8.png)

**Comment by snakorse** [comment]
It's not ready for production, this branch maybe deprecated I think, more discussion at #51 .

**Comment by liuhaoyang** [comment]
coreclr_profiler branch is no longer maintained.
