### ISSUE TITLE
目前可以集成Nlog日志信息吗？

### ISSUE THREAD

**Issue by neil-he** [SkyAPM/SkyAPM-dotnet#403]
关注到目前SkyWalking8.4出现了个日志Tab，可以根据每一条追踪信息查看对应的日志。看了下官网里面支持logback，log4j等日志组件，想问下，我们的这个组件，如何配置可以集成nlog日志呢？
![QQ截图20210406163243](https://user-images.githubusercontent.com/17306587/113682461-c15a3300-96f5-11eb-8e9d-d93635711069.png)

**Comment by snakorse** [comment]
This feature is not implemented yet, it's on the planning list.

**Comment by snakorse** [comment]
move to #418

**Comment by wu-sheng** [comment]
Once dot net agent could inject trace context in log text, filebeat and fluentd are on incoming supported list to collect and analysis logs. You don't need log reporter by yourself actually.
