### ISSUE TITLE
How to set monitoring for SqlClient？

### ISSUE THREAD

**Issue by knowyi** [SkyAPM/SkyAPM-dotnet#413]
Project environment net5, ORM uses dapper. I want to monitor SqlClient. Now I can only see HTTP requests, but I can't see SQL trace. Is there a problem with the settings

![image](https://user-images.githubusercontent.com/7392434/116066007-2af8ac00-a6ba-11eb-8f4c-93a7e9788182.png)

![image](https://user-images.githubusercontent.com/7392434/116065570-bc1b5300-a6b9-11eb-9673-4af5ff392fd4.png)
![image](https://user-images.githubusercontent.com/7392434/116065662-d0f7e680-a6b9-11eb-952a-612f026b8920.png)

**Comment by snakorse** [comment]
I think you are probably using the `Microsoft.Data.SqlClient` package. if so, you should upgrade skyapm to latest prerelease version of 1.3.0 from MyGet source. The 1.2.0 version indeed can not work with `Microsoft.Data.SqlClient`. related mr #387
