### ISSUE TITLE
How to setup skyapm in a system both having netcore2.1 and netcore3.1 services?

### ISSUE THREAD

**Issue by redochenzhen** [SkyAPM/SkyAPM-dotnet#414]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
For what I can tell, the highest version that support netcore2.1 is v0.9.0, which is only compatable with skywalking 7.x. And we use agent v1.2.0 (with skywalking 8.x) in our netcore3.1 projects. 
So, how to solve this problem in a system both using netcore2.1 and netcore3.1?

**Comment by snakorse** [comment]
In theory, skyapm v1.x can work with platforms that support netstandard 2.0, including netcoreapp2.1. So what's the problem you encountered when using skyapm v1.2.0 with netcoreapp2.1?

**Comment by redochenzhen** [comment]
There is a dependency conflict between skyapm v1.2.0 and netcoreapp2.1.
>  Sample.NetCore2_1 -> SkyAPM.Agent.AspNetCore 1.2.0 -> SkyAPM.Agent.Hosting 1.2.0 -> SkyAPM.Utilities.Logging 1.2.0 -> Microsoft.Extensions.Logging 3.1.0 -> Microsoft.Extensions.Configuration.Binder 3.1.0 -> Microsoft.Extensions.Configuration (>= 3.1.0) 
 Sample.NetCore2_1 -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Configuration (>= 2.1.1 && < 2.2.0).

**Comment by snakorse** [comment]
Move to #419.
