### ISSUE TITLE
How to setup skyapm in full .net framework project?

### ISSUE THREAD

**Issue by redochenzhen** [SkyAPM/SkyAPM-dotnet#415]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What I did:
1. install nuget package: SkyApm.Agent.AspNet v1.2.0
2. add skyapm.json (sw8/v8)
But nothing happens appearing on skywalking portal.
- Occasionally I did this:
1. install nuget package: NewRelic.Agent.Api
2. appy TraceAttribute to the action of the controller
It works.

**Comment by snakorse** [comment]
It should be work with .netframeworks supporting netstandard 2.0. Are you still have problem playing with .net framework?

**Comment by redochenzhen** [comment]
Yep. Both v1.20 and v1.3.0 woke fine for me. 
I think this issue should be closed now. Greate thanks!
