### ISSUE TITLE
SkyAPM.Agent.AspNet v1.2.0,  website .netframework4.7.2  not support?

### ISSUE THREAD

**Issue by sw1136562366** [SkyAPM/SkyAPM-dotnet#417]
### website not support?
- SkyAPM.Agent.AspNet v1.2.0
- visual studio  create website project ( .netframework4.7.2)
![image](https://user-images.githubusercontent.com/31207341/117538089-18299400-b037-11eb-8079-1b7e9530af35.png)
![image](https://user-images.githubusercontent.com/31207341/117538134-57f07b80-b037-11eb-8497-d2e4e6e943a0.png)
- No data is reported and no log is generated for the startup project
- Does SkyAPM.Agent.AspNet only support WebApplication project?

**Comment by redochenzhen** [comment]
Hi sw1136562366,
According to my experience, it doesn't work even in WebApplication (net462 or net472). #415
Does it work for you?

**Comment by sw1136562366** [comment]
> Hi sw1136562366,
> According to my experience, it doesn't work even in WebApplication (net462 or net472). #415
> Does it work for you?

SkyAPM.Agent.**AspNet v1.2.0**  support  WebApplication (net462 or net472), It works fine

**Comment by sw1136562366** [comment]
> Hi sw1136562366,
> According to my experience, it doesn't work even in WebApplication (net462 or net472). #415
> Does it work for you?
[#366 ](
https://github.com/SkyAPM/SkyAPM-dotnet/pull/366)

**Comment by redochenzhen** [comment]
Thanks for your quick response. I will check it latter.

**Comment by snakorse** [comment]
@sw1136562366 cound you please upload a demo project codes reproducing it?

**Comment by feiyun0112** [comment]
@sw1136562366 

can you close this issue or give more details?
