### ISSUE TITLE
Log & Trace integration

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/SkyAPM-dotnet#418]
SkyWalking is enhancing its log integration capability, so, it will accept logs collected by popular tools, such as fluentd, filebeat.
It is better dotnet agent could inject the trace context information as a part of log text, which could make SkyWalking backend links logs and traces together.
You could take Java agent's implementation for a reference, http://skywalking.apache.org/docs/main/v8.5.0/en/setup/service-agent/java-agent/application-toolkit-log4j-1.x/#print-skywalking-context-in-your-logs

**Comment by hepinggege** [comment]
1.4.0 版本大概什么时候可以发布呢？

**Comment by zhujinhu21** [comment]
同问大佬，1.4大概时候发布，谢谢

**Comment by sjdboy** [comment]
> 同问大佬，1.4大概时候发布，谢谢

快了，现在80%了。感谢大佬辛苦。

**Comment by myokok** [comment]
大佬大佬，1.4大概时候发布，谢谢

**Comment by myokok** [comment]
大佬，都2022年了，日志好了么？急等啊。

**Comment by wu-sheng** [comment]
@myokok This is an open-source project, not a service. If someone wants to contribute, it could be there. That is all.
