### ISSUE TITLE
Can't setup to SkyAPM.Agent.AspNet v1.3.0 to netcore2.2 project

### ISSUE THREAD

**Issue by thomaspeng90s** [SkyAPM/SkyAPM-dotnet#419]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I setup SkyAPM.Agent.AspNet v1.3.0 to netcore2.2 project, but it requires netcore3.1.
Then I tried to setup SkyAPM.Agent.AspNet v1.3.0 to a standard 2.0 project, but there is a dependency conflict between skyapm v1.3.0 and my project.
![image](https://user-images.githubusercontent.com/25027712/118780061-3f495680-b8be-11eb-8359-7d04bd9b5f74.png)

So what should I do to make it works?

**Comment by snakorse** [comment]
@ElderJames I found this pr(#276 ) upgraded the `Microsoft.Extensions.xxx` to v3.1.0, is it an intention to drop support for netcoreapp2.1? or just a mistaken?

**Comment by ElderJames** [comment]
Sorry about that, it is a mistake indeed. I didn't do the 2.x compatibility. It should need to add compile conditions to support 2.x.

**Comment by liuhaoyang** [comment]
@ElderJames Can you fix this problem ?

**Comment by ElderJames** [comment]
Sure.

**Comment by feiyun0112** [comment]
@thomaspeng90s 

.NET Core 2.1 is no longer supported, can you close this issue?

**This project currently supports apps targeting netcoreapp3.1、net5.0、net6.0 or higher.**
