### ISSUE TITLE
Does it support Asp.Net website(.net framework 4.7.2) project?

### ISSUE THREAD

**Issue by SuperFireFoxy** [SkyAPM/SkyAPM-dotnet#420]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
- SkyApm.Agent.AspNet
- Win10
- .net framework 4.7.2

- What happen?
It seems the current `SkyApm.Agent.AspNet` can't send any data to Skywalking server.

___
### Requirement or improvement
- Do you have any plan to support this project type?

**Comment by ElderJames** [comment]
duplicate with #417

**Comment by snakorse** [comment]
@SuperFireFoxy  cound you please upload a demo project codes reproducing it?
