### ISSUE TITLE
will the project update to .net core 5.0?

### ISSUE THREAD

**Issue by Mrmantou** [SkyAPM/SkyAPM-dotnet#422]
will the project update to .net core 5.0?

**Comment by snakorse** [comment]
Skyapm should compatible with .net5.0, do you have problem working with .net5.0?

**Comment by feiyun0112** [comment]
@Mrmantou 

**This project currently supports apps targeting netcoreapp3.1、net5.0、net6.0 or higher.**

can you close this issue?
