### ISSUE TITLE
dotnetcore 3.1 or 5.0 can not receive data

### ISSUE THREAD

**Issue by willis0591** [SkyAPM/SkyAPM-dotnet#425]
![image](https://user-images.githubusercontent.com/37576675/121666223-95837100-cadb-11eb-9b4d-0aced4c01c56.png)
I'm use skywalking-kubernetes 8.5.0 , dotnetcore 5.0 project,name:api-eims, "SkyAPM.Agent.AspNetCore" Version="1.3.0",View agent log output is normal. but no api-eims information is obtained on the skywalking server, Today I upgraded skywalking to version 8.6.0, but the problem remains, Check the oap and ui logs, and there is no error message,Can you provide some troubleshooting ideas?

**Comment by snakorse** [comment]
1. ensure you select the correct time range at the right bottom corner of skywalking UI
2. check the skywalking logs if any error occur

**Comment by willis0591** [comment]
I confirm that my time selection is correct, because there is also a java project that can be displayed normally.

**Comment by willis0591** [comment]
When will the nuget v1.4.0 package be released? Will v1.4.0 solve the support of dotnetcore 2.0 and 3.0? Maybe v1.4.0 version can resolve my problem.

**Comment by liuhaoyang** [comment]
Can you post more logs, or provide a demo to reproduce the problem?

**Comment by willis0591** [comment]
[skywalking-oap.log](https://github.com/SkyAPM/SkyAPM-dotnet/files/6691499/skywalking-oap.log)
[skyapm-20210622.log](https://github.com/SkyAPM/SkyAPM-dotnet/files/6691501/skyapm-20210622.log)

**Comment by h82258652** [comment]
Change HeaderVersions to sw8 and ProtocolVersion to v8 in skyapm.json solve my problem.
