### ISSUE TITLE
Unable to collect data from Pomelo.EntityFrameworkCore.MySql correctly

### ISSUE THREAD

**Issue by virgil-wang** [SkyAPM/SkyAPM-dotnet#427]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug v1.3.0 
When I Used `Pomelo.EntityFrameworkCore.MySql v5.0.0` ,SkyApm v1.3.0 failed to resolve span component name and peer.

![1](https://user-images.githubusercontent.com/34264277/123608358-448cb000-d831-11eb-8830-43a6b648582a.png)

I found the problem is in https://github.com/SkyAPM/SkyAPM-dotnet/blob/36ff3204a8dcc5682b5bcda9f33ff64e81afad20/src/SkyApm.Diagnostics.EntityFrameworkCore.Pomelo.MySql/MySqlEntityFrameworkCoreSpanMetadataProvider.cs#L29

`Pomelo.EntityFrameworkCore.MySql` has used `MySqlConnector.MySqlConnection`  instead of `MySql.Data.MySqlClient.MySqlConnection` a long time ago.

Then I downgraded the `Pomelo.EntityFrameworkCore.MySlq` to v1.1.2, this time the peer field was parsed correctly but not the component.

![2](https://user-images.githubusercontent.com/34264277/123622653-131ae100-d83f-11eb-8f03-91eb2736fbb4.png)

I guess the problem is
https://github.com/SkyAPM/SkyAPM-dotnet/blob/b35a9e547cf6b0b39f1edd0cd8920971b7b4e4b3/src/SkyApm.Diagnostics.EntityFrameworkCore/EntityFrameworkCoreSegmentContextFactory.cs#L73
https://github.com/SkyAPM/SkyAPM-dotnet/blob/b35a9e547cf6b0b39f1edd0cd8920971b7b4e4b3/src/SkyApm.Abstractions/Common/StringOrIntValue.cs#L38-L42
https://github.com/SkyAPM/SkyAPM-dotnet/blob/b35a9e547cf6b0b39f1edd0cd8920971b7b4e4b3/src/SkyApm.Transport.Grpc/Common/SegmentV8Helpers.cs#L108

when we use `new StringOrIntValue(metadataProvider.Component)`，the `_intValue` was set **0**, but `SegmentV8Helpers.ComponentReader` is nolonger used,so an **Unknown Component** was send to skywalking-oap-server.

**Comment by feiyun0112** [comment]
@virgil-wang 

please close this issue.
