### ISSUE TITLE
How to add Cap and SamrtSql support.

### ISSUE THREAD

**Issue by xiangxiren** [SkyAPM/SkyAPM-dotnet#430]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How to add Cap support. In version 0.9.0, the AddCap method is called by default. However, it was removed in subsequent adjustments. How to register `CapTracingDiagnosticProcessor` now? SmartSql has the same problem.

**Comment by feiyun0112** [comment]
you can use `services.AddXXX` in startup.cs

sample code:

https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/sample/SkyApm.Sample.SmartSql/Startup.cs#L30
