### ISSUE TITLE
can't write data to skywalking

### ISSUE THREAD

**Issue by ClementeGao** [SkyAPM/SkyAPM-dotnet#431]
env:
skywalking-oap-server  latest
SkyAPM.Agent.AspNetCore 1.3.0
netcore 3.1
![image](https://user-images.githubusercontent.com/16145998/126256299-1cbdbebb-552c-4f33-813b-d48c8bce34f6.png)

no data?
![image](https://user-images.githubusercontent.com/16145998/126256319-623a9f68-8f4b-4c9f-b22d-387136ac546f.png)

**Comment by xiangxiren** [comment]
Are environment variables set? Is there a log file?

**Comment by ClementeGao** [comment]
yes  i did it now it work well  because my sky env has problem    thank you
