### ISSUE TITLE
Can I customize the tracking ID?

### ISSUE THREAD

**Issue by saber-wang** [SkyAPM/SkyAPM-dotnet#434]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
___
### Question
Can I customize the tracking ID? I want to use the id provided by system.diagnostics.activity.current(w3c). 
dapr tracing(w3c): https://docs.dapr.io/developing-applications/building-blocks/observability/w3c-tracing/w3c-tracing-overview/

https://github.com/SkyAPM/SkyAPM-dotnet/blob/36ff3204a8dcc5682b5bcda9f33ff64e81afad20/src/SkyApm.Core/Tracing/UniqueIdGenerator.cs#L44
Is there any special meaning?

**Comment by wu-sheng** [comment]
I think we don't recommend you to manipulate trace id. This will cause many many unreasonable bug.

**Comment by saber-wang** [comment]
@wu-sheng  Can dapr tracing be supported

**Comment by wu-sheng** [comment]
> @wu-sheng Can dapr tracing be supported

I don't know what is dapr tracing. If their community wants to set a meeting to talk, I am glad to join.

**Comment by saber-wang** [comment]
@wu-sheng  https://docs.dapr.io/developing-applications/building-blocks/observability/tracing-overview/  
Dapr has his own tracking(w3c),At present, I can't merge skywalking and dapr requests. I expect to use the same tracking ID at least, so this problem arises  `(*>﹏<*)′

**Comment by wu-sheng** [comment]
What they do is their choice, SkyWalking could either send some pull requests to add our plugins or just ask them to propagate our headers transparently.
Dapr is not very different from Service Mesh, we have contributors to put our native Tracer in Envoy, you could do similar things in Dapr if you like.

**Comment by wu-sheng** [comment]
This is not a trace id level discussion at all.

**Comment by saber-wang** [comment]
@wu-sheng Thanks.
