### ISSUE TITLE
I want to  log sql parameter.

### ISSUE THREAD

**Issue by zhujinhu21** [SkyAPM/SkyAPM-dotnet#435]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to log sql parameter.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking 8.7 ,net core 2.2
- Which company or project?
SkyApm.Sample.Backend record sql

___
### Requirement or improvement
i foud the code and FormatParameters method parameter is false. why. can i modify is true ,or can i control it through config.

```java
       private string BuildParameterVariables(DbParameterCollection dbParameters)
        {
            if (dbParameters == null)
            {
                return string.Empty;
            }

            return dbParameters.FormatParameters(false);
        }
```

**Comment by feiyun0112** [comment]
@zhujinhu21 

please close this issue.

#441
