### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by niuhao001988** [SkyAPM/SkyAPM-dotnet#443]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion
- [1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Did Skywalking support x86 .netframe project？If support ，how to config？
 ___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
1.3.0/0.8.0   windows10   4.6.1
- Which company or project?

- What happen?
I have an old x86 .net framwork project then use skywalking report an error below

<HTML data-dpmaxz-wbid="2781"><HEAD><TITLE>未能加载文件或程序集“grpc_csharp_ext.x64.dll”或它的某一个依赖项。该模块应包含一个程序集清单。</TITLE>                  
<STYLE>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </STYLE>
     </HEAD><BODY bgcolor="white"><FONT face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif "><TABLE width="100%" bgcolor="#ffffcc"><TBODY><TR><TD><CODE><PRE>[BadImageFormatException: 未能加载文件或程序集“grpc_csharp_ext.x64.dll”或它的某一个依赖项。该模块应包含一个程序集清单。]

[BadImageFormatException: 未能加载文件或程序集“grpc_csharp_ext.x64.dll”或它的某一个依赖项。该模块应包含一个程序集清单。]
   System.Reflection.AssemblyName.nGetFileInformation(String s) +0
   System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile) +87
   Bingosoft.Core.Reflection.Assemblies..cctor() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Core\Reflection\Assemblies.cs:65

[TypeInitializationException: “Bingosoft.Core.Reflection.Assemblies”的类型初始值设定项引发异常。]
   Bingosoft.Core.Ioc.UnityObjectContainer.InitUnityContainer(App application) in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Core\Ioc\UnityObjectContainer.cs:307
   Bingosoft.Core.Ioc.UnityObjectContainer.Create(App application) in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Core\Ioc\UnityObjectContainer.cs:28
   Bingosoft.Core.App.CreateInstance() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Core\App.cs:173
   Bingosoft.Core.App.GetCurrent() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Core\App.cs:117
   Bingosoft.Data.DaoFactory.InitializeActionExecutors() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Data\DaoFactory.cs:340
   Bingosoft.Data.DaoFactory.Initialize() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Data\DaoFactory.cs:290
   Bingosoft.Data.DaoFactory..cctor() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Data\DaoFactory.cs:39

[TypeInitializationException: “Bingosoft.Data.DaoFactory”的类型初始值设定项引发异常。]
   Bingosoft.Data.Dao.Get() in E:\project-dotnet\Bingosoft.Framework\sources\Core\Bingosoft.Data\Dao.cs:27
   Bingosoft.TIW.Services.Common.CommonService..ctor() in D:\02.workspace\93.VSProjects\02.QMM_JL\qmm_jl_test2\Bingosoft.TIW\Bingosoft.TIW\Bingosoft.TIW\Services\Common\CommonService.cs:28
   Bingosoft.TIW.WebApp.Modules.TIW.Common.TIWCommon.SetLanguageData() in D:\02.workspace\93.VSProjects\02.QMM_JL\qmm_jl_test2\Bingosoft.TIW\Bingosoft.TIW\Bingosoft.TIW.WebApp\Modules\TIW\Common\TIWCommon.cs:1318
   Bingosoft.WebApp.Global.Application_Start(Object sender, EventArgs e) in D:\02.workspace\93.VSProjects\02.QMM_JL\qmm_jl_test2\Bingosoft.TIW\Bingosoft.TIW\Bingosoft.TIW.WebApp\Global.asax.cs:18

[HttpException (0x80004005): “Bingosoft.Data.DaoFactory”的类型初始值设定项引发异常。]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +10106399
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +123
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +181
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +228
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +314

[HttpException (0x80004005): “Bingosoft.Data.DaoFactory”的类型初始值设定项引发异常。]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10086640
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +99
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +263
</PRE></CODE></TD></TR></TBODY></TABLE></FONT></BODY></HTML>
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
fixed
