### ISSUE TITLE
【Question】can skyapm-dontnet-1.3.0 support dapper diagnostic?

### ISSUE THREAD

**Issue by walt-liuzw** [SkyAPM/SkyAPM-dotnet#445]
Please answer these questions before submitting your issue.

this is a question
___
### Question
- What do you want to know?

my webapp is based on netcore2.x, i want to diagnostic something adout my webapp databse repository.

can i to do that by referring to skyapm-dontnet-1.3.0 package

**Comment by sampsonye** [comment]
dapper just an sqlhelper wrapper。this skyapm record info from sqlclient

**Comment by sampsonye** [comment]
dapper just an sqlhelper wrapper。this skyapm record info from sqlclient
