### ISSUE TITLE
能否新增手动Startup注入方式

### ISSUE THREAD

**Issue by bao2314483** [SkyAPM/SkyAPM-dotnet#446]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
能否新增手动Startup注入方式,可指定配置Key,或者通过代码写配置方式
```
//可指定配置
services.AddSkyAPM(Configuration.GetSection("SwConfig"));
//手动代码写死配置
services.AddSkyAPM(x=> {
   x.ServiceName = "general-host-sample";
   x.Namespace = "";
    //更多配置信息
 });
```

**Comment by hiwjcn** [comment]
使用这种方式也可以解决 #451 提到的问题
