### ISSUE TITLE
custom tag in the netcore project

### ISSUE THREAD

**Issue by anjoy8** [SkyAPM/SkyAPM-dotnet#456]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Can I make a custom tag in the netcore project, just like this one in java?
ActiveSpan.tag("input", request));

**Comment by ShaoHans** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wu-sheng** [comment]
You could only extend to write a plugin to do so. Right now, no API bridge is available in this agent.
