### ISSUE TITLE
Publishing a project containing SkyAPM.Agent.AspNetCore fails with downgrade

### ISSUE THREAD

**Issue by bingxueyinlian** [SkyAPM/SkyAPM-dotnet#466]
### Question
- What do you want to know?
Publishing a project containing SkyAPM.Agent.AspNetCore fails with downgrade

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
- SkyAPM.Agent.AspNetCore 1.3.0
- Windows 10-2004
- VS 2022 17.1.3
- .net 5.0.403

- What happen?
build succeeds, but publishing fails
![image](https://user-images.githubusercontent.com/1235035/161879743-a6bcf976-1046-4410-af81-0ba4590ea4a0.png)
___
### Requirement or improvement
- Expect publishing to be successful

**Comment by ShaoHans** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by feiyun0112** [comment]
@bingxueyinlian 

I can not reproduce it
can you attach a minimal reproduction project?

**Comment by bingxueyinlian** [comment]
I got it, had to manually add a reference to System.IO.FileSystem 4.3.0 for each project
