### ISSUE TITLE
skyapm.json配置文件中能支持设置servers环境变量或更多的值吗，像设置ServiceName一样

### ISSUE THREAD

**Issue by jiangxiaobai** [SkyAPM/SkyAPM-dotnet#468]
抱歉，当前不支持变量的写法，但我觉得变量这个想法值得考虑

_Originally posted by @snakorse in https://github.com/SkyAPM/SkyAPM-dotnet/issues/367#issuecomment-767339050_

**Comment by wu-sheng** [comment]
There is no point to start an issue including a comment.
