### ISSUE TITLE
Can skywalking collect input parameters and output result parameters of the microservice api?

### ISSUE THREAD

**Issue by fisea001** [SkyAPM/SkyAPM-dotnet#480]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement

___
### Question
- What do you want to know?
I want to use skyamp to collect input parameters and output result parameters of the microservice api?
then dispaly skywalking ui.
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
skywalking is 8.6, skyapm is 1.3
- Which company or project?
project
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by feiyun0112** [comment]
you can collect body by config `CollectBodyContentTypes`

https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/sample/SkyApm.Sample.Frontend/skyapm.json
