### ISSUE TITLE
protocol-v3

### ISSUE THREAD

**Issue by SpringHgui** [SkyAPM/SkyAPM-dotnet#481]
这个项目的文件怎么不提供 SkyAPM-dotnet\src\SkyApm.Transport.Grpc.Protocol\protocol-v3，本地怎么编译

**Comment by wu-sheng** [comment]
可以从CI学习如何编译 https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/.github/workflows/ci-it.yml#L21
