### ISSUE TITLE
pulbish 2.0.0 version SkyApm.Diagnostics.Grpc.Net.Client to fix error 'Could not load type 'SkyApm.Diagnostics.DiagnosticName' from assembly 'SkyAPM.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01'.'

### ISSUE THREAD

**Issue by leisurelyclouds** [SkyAPM/SkyAPM-dotnet#487]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
2.0.0 SkyAPM
- Which company or project?
SkyApm.Diagnostics.Grpc.Net.Client
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
install SkyAPM 2.0.0 and add line in ConfigureServices method will throw exception `Could not load type 'SkyApm.Diagnostics.DiagnosticName' from assembly 'SkyAPM.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01'.`
```
services.AddSkyAPM(ext => ext.AddAspNetCoreHosting());
```

### Reason
`SkyAPM.Agent.AspNetCore` Version=2.0.0
depend
- `SkyAPM.Core` Version=2.0.0
- `SkyApm.Diagnostics.Grpc.Net.Client` Version=1.0.0 

But

`SkyApm.Diagnostics.Grpc.Net.Client` Version=1.0.0
depend
- `SkyAPM.Core` Version=1.0.0
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lijing3232** [comment]
I have the same problem. Is it possible to fix it asap?

**Comment by leisurelyclouds** [comment]
> I have the same problem. Is it possible to fix it asap?

download source code and add cs project reference 
or
build source code and publish private nuget package

**Comment by EricChoi007-coder** [comment]
Encouter the same problem. Any chance we can fix it by some config or quick method?

**Comment by liuhaoyang** [comment]
Version 2.0.1 fixes this issue.
