### ISSUE TITLE
window11 arm64

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [SkyAPM/SkyAPM-dotnet#488]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
[Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: Y:\test\sample2.Web\bin\Debug\net6.0\grpc_csharp_ext.arm64.dll,Y:\test\sample2.Web\bin\Debug\net6.0\runtimes/win-arm64/native\grpc_csharp_ext.arm64.dll
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by zhanghaiboshiwo** [comment]
.net 6

**Comment by liuhaoyang** [comment]
It may be that grpc.net does not support arm64
