### ISSUE TITLE
MassTransit support

### ISSUE THREAD

**Issue by cocosip** [SkyAPM/SkyAPM-dotnet#500]
- [ ] Requirement

___
### Requirement or improvement
- Any plan support MassTransit ?  [doc](https://masstransit-project.com/advanced/monitoring/diagnostic-source.html)

**Comment by BoydenYubin** [comment]
Please note that the version of doc you mentioned is below v8.0.0, the ner version of Masstransit has uesd Activity and ActivitySource.
