### ISSUE TITLE
Automatic-Agent based on CLR Profiling API

### ISSUE THREAD

**Issue by liuhaoyang** [SkyAPM/SkyAPM-dotnet#51]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

In the CLR, the [profiling API](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/profiling-overview) is used to write a code profiler, which is a program that monitors the execution of a managed application. We can use the JIT recompilation methods in the [ICorProfilerCallback4](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback4-interface) interface, to insert SkyWalking's tracing logic in the target method. For SkyWalking .NET Core Agent, this will be a very important change, realizing automatic proxy means that SkyWalking-NetCore will be comparable to some commercial APM products.

**Comment by wu-sheng** [comment]
That will be an important and attractive feature.

**Comment by MetSystem** [comment]
类似这种吗
https://github.com/HDJN/Pinpoint.Agent.DotNet

**Comment by liuhaoyang** [comment]
@MetSystem The implementation mechanism is similar. Difference is that we will provide cross-platform (windows, linux and OSX) automatic-agent, not just windows-only.

**Comment by wu-sheng** [comment]
> 类似这种吗
https://github.com/HDJN/Pinpoint.Agent.DotNet

@MetSystem This looks like a dead project. No further commit, and no release.

**Comment by MetSystem** [comment]
对的，已经没有维护。
相比pp我还是比较喜欢skywalking

**Comment by MetSystem** [comment]
5.0bate v5

**Comment by kingreatwill** [comment]
https://github.com/DataDog/dd-trace-csharp  这个好像是基于profiling API实现的agent

**Comment by liuhaoyang** [comment]
> https://github.com/DataDog/dd-trace-csharp 这个好像是基于profiling API实现的agent

We have found that the profiling api has compatibility issues on macOS/Linux. If you are interested in the profiling api, you can contribute on [coreclr_profiler](https://github.com/OpenSkywalking/skywalking-netcore/tree/coreclr_profiler) branch .

**Comment by caozhiyuan** [comment]
https://github.com/caozhiyuan/clr-samples  i work  it , now it has two ways to trace method . if you want use profiling API can refer it . @liuhaoyang

**Comment by liuhaoyang** [comment]
Thank you. Are you interested in re-implementing clrprofiler for skywalking? @caozhiyuan

**Comment by caozhiyuan** [comment]
in net core has System.Diagnostics.TraceSource , but some package don't impl it . 
in net framework , just httpwebrequest microsoft do it.
clrprofiler has more flexibility , it like java skywalking agent byte-buddy.
if re-implementing clrprofiler for skywalking will spent some time. 
now i do clrprofiler  feasibility study and write demo. 
if do it for skywalking , it is not a probelm, but it need make some design.

**Comment by caozhiyuan** [comment]
it's base https://github.com/Microsoft/clr-samples ,it's ok.

**Comment by liuhaoyang** [comment]
This sample is too simple, it does not use the high-level api of coreclr. I have [tried](https://github.com/OpenSkywalking/skywalking-netcore/tree/coreclr_profiler), the difference between standard c++ and vc++ is really too big.

**Comment by liuhaoyang** [comment]
I reopened the issue and interested people can continue to pay attention. Our goal is to implement an across platforms coreclr-profiler  (at least including windows, linux and macOS). If it doesn't work on a certain platform, I would rather use `DiagnosticSource` to do it.

**Comment by caozhiyuan** [comment]
some apm has run in linux. i will try compile it on linux. now i try get pe entrypoint main mdtoken, so we can hook il code in premain , it no need DOTNET_ADDITIONAL_DEPS.

**Comment by liuhaoyang** [comment]
You are right. `DOTNET_ADDITIONAL_DEPS` does cause a lot of confusion for the user.

**Comment by liuhaoyang** [comment]
> some apm has run in linux. i will try compile it on linux. now i try get pe entrypoint main mdtoken, so we can hook il code in premain , it no need DOTNET_ADDITIONAL_DEPS.

If you have any progress, please discuss it together. I also have a lot of interest in clrprofiler.

**Comment by caozhiyuan** [comment]
@liuhaoyang  i finished premain ,  tomorrow i try built it on linux

**Comment by caozhiyuan** [comment]
https://github.com/caozhiyuan/clr-samples/blob/master/ProfilingAPI/ClrProfiler/build.sh
linux build is done, next i will add json config to define trace method info @liuhaoyang

**Comment by caozhiyuan** [comment]
yes , you can

**Comment by liuhaoyang** [comment]
FYI @caozhiyuan This is the [roadmap#v0.9.0](https://github.com/OpenSkywalking/skywalking-netcore/blob/master/docs/roadmap.md#v090) for the skywalking .net core .   In v0.8.0, I will focus on fix known bugs in the issue list.. In version 0.90, let's complete the clr profiler. What do you think?

**Comment by caozhiyuan** [comment]
ok @liuhaoyang  about c# agent  , need i contribute some code or you can finish it?  seems clrprofiler no need Diagnostics source .

**Comment by liuhaoyang** [comment]
If you can help, that would be great. One more thing we need to consider, how does clrprofiler design a plugin mechanism?

**Comment by caozhiyuan** [comment]
@liuhaoyang  i  exampled a plugin mechanism for handle dll dependency problem, and use ILRepack to make trace core dll no dependency .

https://github.com/caozhiyuan/ClrProfiler.Trace/blob/master/src/ClrProfiler.Trace/MethodFinderService.cs

**Comment by caozhiyuan** [comment]
i write a skyapm clrprofiler sample at here: https://github.com/caozhiyuan/SkyAPM-dotnet/tree/clrprofiler/src @liuhaoyang  can i make a pull request?

**Comment by liuhaoyang** [comment]
> 我在这里写了一个skyapm clrprofiler样本：[https](https://github.com/caozhiyuan/SkyAPM-dotnet/tree/clrprofiler/src) ：[//github.com/caozhiyuan/SkyAPM-dotnet/tree/clrprofiler/src ](https://github.com/caozhiyuan/SkyAPM-dotnet/tree/clrprofiler/src)@liuhaoyang 我可以提出拉取请求吗？

Of course. If you can create a PR, it would be great.

**Comment by caozhiyuan** [comment]
@liuhaoyang please create a new clrprofiler branch , old clr-profiler branch may be have some conflict

**Comment by liuhaoyang** [comment]
> @liuhaoyang please create a new clrprofiler branch , old clr-profiler branch may be have some conflict

I have created a new [coreclr_profiler](https://github.com/SkyAPM/SkyAPM-dotnet/tree/coreclr_profiler) branch based on master

**Comment by caozhiyuan** [comment]
@liuhaoyang  next , need you do some effort on clrprofiler . about incompatible with master 、more test、release。

in profiler brach use azure-pipeline , master has cake build and appveyor ci.
master brach Diagnostics will how to be handle.

**Comment by liuhaoyang** [comment]
> @liuhaoyang 接下来，需要你对clrprofiler做一些努力。关于与master不兼容，更多测试，发布。
> 
> 在profiler brach中使用azure-pipeline，master有cake build和appveyor ci。
> master brach Diagnostics将如何处理。

First of all, thank you for the profiler code provided, which is a very important step. Next I will deal with the conflict with the existing code, improve the release process, and guide the user to use the profiler agent, until the profiler can be used in the user's production environment.

**Comment by liuhaoyang** [comment]
In the practice of skyapm-dotnet for two years, we have been trying to find a more suitable way to write dotent instrument. Although CLR profiling API can achieve our goal, but from the actual situation, CLR profiling API has a high threshold for most dotnet developers, so I prefer to use high-level APIs with limited functions, such as `DiagnosticSource` and `Eventpipe`. high-level APIs can make it easier for contributors to participate.
