### ISSUE TITLE
asp.net framework 4.8 安装存在依赖包版本不兼容的情况，请问该如何解决呢

### ISSUE THREAD

**Issue by hxd123456** [SkyAPM/SkyAPM-dotnet#523]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
asp.net framework 4.8 安装存在依赖包版本不兼容的情况，请问该如何解决呢，当我通过直接拷贝dll到项目下时可以解决，但是又会出现其他依赖无法找到的情况，原因似乎是由于同一个应用程序域中无法存在多个版本的同一依赖导致的，请问我应该如何去解决呢
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
- SkyWalking：1.3.0
-  OS：Windows
- .NET Runtime：net framework 4.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

![image](https://user-images.githubusercontent.com/46563086/201257583-d581afb0-50d6-434f-bd15-ae2d75985a0a.png)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
推荐使用 ASP.NET Core  对.NET Framework的支持已经移除
