### ISSUE TITLE
Change the span of EntityFrameworkCore to Exit

### ISSUE THREAD

**Issue by saber-wang** [SkyAPM/SkyAPM-dotnet#524]
https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-database/

The `virtual database` requires that the span must be `exit`. Currently, only some supports are set to `exit`.
https://github.com/SkyAPM/SkyAPM-dotnet/blob/000c990c76aafa43ec0bc23d9ccc7ad5a347dde3/src/SkyApm.Diagnostics.EntityFrameworkCore/EntityFrameworkCoreSegmentContextFactory.cs#L51

**Comment by wu-sheng** [comment]
Yes, `exit` span is required for all `virtual` analysis. Contributions are welcome.
