### ISSUE TITLE
咨询skywalkin-ui 里面的 service groups 在SkyAPM-dotnet中怎么设置。

### ISSUE THREAD

**Issue by AlphaYu** [SkyAPM/SkyAPM-dotnet#526]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
各位大佬，咨询两个问题。
1、skywalkin-ui 里面的 service groups 在[SkyAPM-dotnet](https://github.com/SkyAPM/SkyAPM-dotnet)中怎么设置。
2、SkyWalking 配置节点中的Namespace表示什么意思。
```json
{
  "SkyWalking": {
    "ServiceName": "adnc-xxx",
    "Namespace": ""
  }
}
```

**Comment by zhh007** [comment]
这样配置："testoa_pc::demo"
