### ISSUE TITLE
是否有较完整的使用文档

### ISSUE THREAD

**Issue by MyNine** [SkyAPM/SkyAPM-dotnet#534]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
目前没有较完整的使用文档，同时代码中注释很少，只能通过提问，或者翻找issue来找。
希望对于获取traceId，集成log等基础功能至少提供一些较完整的demo
感谢~

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is not how open source works.
Docs exist due to someone wrote, we as maintainers are working as volunteers.
If you want to write, others would have a more detailed doc.
