### ISSUE TITLE
database面板无数据，对应的event

### ISSUE THREAD

**Issue by MyNine** [SkyAPM/SkyAPM-dotnet#535]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
在Trace（追踪）页面可以看到db操作信息 
但是在dashboard（仪表盘）下的Database页面中，无任何数据

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking verison - v8.5.0
SkyAPM.Agent.AspNe v2.1.0
OS:
 Windows 11
.NET Runtime:  .NETCoreApp,Version=v6.0
Microsoft.EntityFrameworkCore/6.0.7
Mysql Ver 8.0.30

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
在追踪页面可以看到对应的db操作
![image](https://user-images.githubusercontent.com/15926435/216910228-c860f7ce-faef-4bb5-8610-255622d1eaaf.png)

但是在仪表盘-Database下数据均为空
![image](https://user-images.githubusercontent.com/15926435/216910507-3f47dac2-d718-4e43-9261-9e0587a623f3.png)

请问是需要做什么额外配置，还是版本不支持呢
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
8.5 is EOL. And event is not supported by .net afaik.

**Comment by MyNine** [comment]
感谢回复！
不好意思，之前标题中的event本意是"EntityFrameCore对应的eventSource存在"; 不知道您回复中的”event“是不是指原标题中的event。
具体还是想请教下，升级SkyWaling到9.X后database界面下会有数据吗。还是说.net下不支持该功能。

**Comment by MyNine** [comment]
> 8.5 is EOL. And event is not supported by .net afaik.

感谢回复！
不好意思，之前标题中的event本意是"EntityFrameCore对应的eventSource存在"; 不知道您回复中的”event“是不是指原标题中的event。
具体还是想请教下，升级SkyWaling到9.X后database界面下会有数据吗。还是说.net下不支持该功能。
