### ISSUE TITLE
如何过滤URL？

### ISSUE THREAD

**Issue by myokok** [SkyAPM/SkyAPM-dotnet#537]
我们的项目里使用了nacos作配置中心和服务注册发现功能，同时我们也接入了 skywalking。
问题：
skywalking里记录了很多 nacos的一些心跳信息，比如：
http://xxx:8848/nacos/v1/cs/configs/listener
如何过滤这些无意义的链接？

![image](https://user-images.githubusercontent.com/44723876/218359628-43da663b-c8c4-482f-a436-ac179262aea7.png)

**Comment by liuhaoyang** [comment]
参考 https://github.com/SkyAPM/SkyAPM-dotnet/blob/main/sample/SkyApm.Sample.Frontend/skyapm.json#L11
