### ISSUE TITLE
请问怎么将SkyAPM-dotnet添加到wpf客户端或者Console客户端，形成一条从客户端到后台api的链路跟踪。

### ISSUE THREAD

**Issue by luchunminglu** [SkyAPM/SkyAPM-dotnet#554]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
我目前已经在asp.net web api里面集成了skyApm-Dotnet，运行正常。

现在我需要在客户端(wpf客户端或者普通Console)使用httpClient调用asp.net web api。
请问怎么将SkyAPM-dotnet添加到wpf客户端或者Console客户端，形成一条从客户端到后台api的链路跟踪。

**Comment by liuhaoyang** [comment]
你可以试试用Core提供的trace API，自己在WPF代码里埋点，或者封装一个WPF Agent
