### ISSUE TITLE
May I ask if the log folder can be named after the month and year

### ISSUE THREAD

**Issue by WuLiang9023** [SkyAPM/SkyAPM-dotnet#556]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by aabb1212** [comment]
hello,this is my way.

https://github.com/aabb1212/Ars/blob/master/SkyApmLogFolderSolution.md

**Comment by bingtianyiyan** [comment]
i suggest if use serilog,apm should add Configuration  read from configfile like
<img width="977" alt="1691659581223" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/48984656/8d63dfbd-42ce-4a54-bb4c-87baa031aa2a">

**Comment by lu-xiaoshuang** [comment]
Pull Requst [557](https://github.com/SkyAPM/SkyAPM-dotnet/pull/557)
