### ISSUE TITLE
Provide dynamic refresh file in agent

### ISSUE THREAD

**Issue by liuhaoyang** [SkyAPM/SkyAPM-dotnet#56]
Sync https://github.com/apache/incubator-skywalking/issues/1181

>This requirement came from the upgrade, SkyWalking's agent and protocol are stable enough, and didn't need to update for a long time. But considering right now, there are a lot of buffer in agent, so end users must reboot the monitored applications to upgrade backend, which caused by backend upgrade is not forward-compatible.
>By having this feature, the backend break upgrade should be:
>1. Stop all backends.
>2. Clear the ElasticSearch data.
>3. Set all flush file to true, and wait all agents refreshed and updated the new refresh time.
>4. Start up new version collector.

**Comment by wu-sheng** [comment]
Be care of this requirement. Even skywalking java agent delayed this to 5.1.0, which should be after GA.

**Comment by liuhaoyang** [comment]
This feature seems to have no progress, I temporarily removed it from the milestone.

**Comment by wu-sheng** [comment]
I am trying to provide refresh from command set by UI. Let me find time to support this after I did slow sql.

I will ping you after that is done.

**Comment by liuhaoyang** [comment]
New progress https://github.com/apache/incubator-skywalking/pull/2380
cc @yang-xiaodong @witskeeper
