### ISSUE TITLE
skywalking前端页面查询不到

### ISSUE THREAD

**Issue by EverCooling** [SkyAPM/SkyAPM-dotnet#569]
<img width="1480" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/83dd0ff8-d8a1-4edf-8efe-6fe963f49bbb">
<img width="1418" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/b177bd72-3f65-45ce-a8ac-b7e3401a12ae">
<img width="798" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/705d6fae-54c4-4412-80ed-c4f5705bad1f">
<img width="646" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/f425947c-5fa5-4389-8db1-e7478b7a4ec4">
<img width="687" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/19c56397-463f-44de-8ba5-ef86159d7725">
在.Net6中配置 skywalking 前端UI不显示服务名称，辛苦帮忙看一下，哪儿有问题的

**Comment by liuhaoyang** [comment]
看看本地的skyapm log文件有没有上报异常的日志？

**Comment by EverCooling** [comment]
> 看看本地的skyapm log文件有没有上报异常的日志？

<img width="2236" alt="image" src="https://github.com/SkyAPM/SkyAPM-dotnet/assets/30490402/cac1e154-6688-481c-9ef6-24031b9d7327">

**Comment by EverCooling** [comment]
> > 看看本地的skyapm log文件有没有上报异常的日志？
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/30490402/273382325-cac1e154-6688-481c-9ef6-24031b9d7327.png">

请教一下，这个是什么原因的呀？

**Comment by goodsxx** [comment]
同问

**Comment by 2741823826GX** [comment]
端口开了嘛？11800和12800都要开，一个是http端口一个是grpc端口
