### ISSUE TITLE
SKYWALKING__SERVICENAME 是否直接支持组名? 或者组名的环境变量是?

### ISSUE THREAD

**Issue by Spinestars** [SkyAPM/SkyAPM-dotnet#570]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?

在JAVA AGENT中, 可以通过环境变量 `SW_AGENT_NAME=<group name>::<logic name>`的方式, 来填充服务组名. 如图所示:

![image](https://github.com/SkyAPM/SkyAPM-dotnet/assets/7272900/d96ae3ac-b781-4564-a862-87368b72d738)

**Comment by wu-sheng** [comment]
Service name is manually set, this is OAP backend feature. The agent doesn't care about this.
