### ISSUE TITLE
How to support multiple environments.

### ISSUE THREAD

**Issue by hxkaka007** [SkyAPM/SkyAPM-dotnet#572]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
The nuget only can get  value of SkyWalking:Transport:gRPC:Servers from skyapm.json, the file of skyapm.QA.json file can't work.

**Comment by wu-sheng** [comment]
No, you can't. All system is designed for microservice, so, no expected multiple services in one process.
