### ISSUE TITLE
CAP trace broken when using latest skyapm-dotnet code

### ISSUE THREAD

**Issue by witskeeper** [SkyAPM/SkyAPM-dotnet#573]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

Mac OS running SkyWalking 9.0.0 in Docker:
```shell
# 安装oap
docker run --name oap -p 11800:11800 -p 12800:12800 --restart always -d apache/skywalking-oap-server:9.0.0

# 安装oap-ui
export version=9.0.0
docker run --name oap-ui -p 8080:8080 -d --link oap -e SW_OAP_ADDRESS=http://oap:12800  apache/skywalking-ui:$version
```

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

using skyapm-donet latest code from main branch.

demo code : <https://github.com/netcorepal/netcorepal-cloud-framework/tree/main/test/NetCorePal.Web>
 
![image](https://github.com/SkyAPM/SkyAPM-dotnet/assets/5594094/cf566fee-0c4e-4886-a393-11ec7498eaa0)

___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Ping @snakorse if you are still watching this repository.

**Comment by witskeeper** [comment]
more info :
the `BeforePublish`  do not show  in trace

**Comment by witskeeper** [comment]
@yang-xiaodong  Can you help us check this issue?

**Comment by witskeeper** [comment]
fixed in #575

**Comment by yang-xiaodong** [comment]
@witskeeper  

`BeforePublish` is propagated based on the EntrySegmentContext created in `BeforePublishStore`. I saw that you judged `_entrySegmentContextAccessor.Context == null` in `BeforePublish` and created the EntrySegmentContext again. In fact, the Context here should not be null. 

Have you configured [SkyApm.Diagnostics.AspNetCore](https://github.com/SkyAPM/SkyAPM-dotnet/tree/main/src/SkyApm.Diagnostics.AspNetCore)?

**Comment by witskeeper** [comment]
configure code like :
```
builder.Services.AddSkyAPM(ext => ext.AddAspNetCoreHosting().AddCap());
```

pulish code like：
```
 [HttpGet]
[Route("/sendEvent")]
public async Task SendEvent(OrderId id,[FromServices]ICarrierPropagator _carrierPropagator)
{
    await capPublisher.PublishAsync("OrderPaidIntegrationEvent", new OrderPaidIntegrationEvent(id), cancellationToken: HttpContext.RequestAborted);
}
```

BeforePublish  dose not run under the async context  in  witch code calling  PublishAsync,
it runs after the  api function  `SendEvent` return.
