### ISSUE TITLE
How to modify the endpoint name of skywalking

### ISSUE THREAD

**Issue by 2741823826GX** [SkyAPM/SkyAPM-dotnet#577]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 怎么修改skywalking Endpoint的名称，我看现在是默认的Endpoint是路由

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
Skywalking9.3

**Comment by wu-sheng** [comment]
都是插件实现决定的
