### ISSUE TITLE
Can you solve the problem of having two instance IDs for the same service after restarting IIS?

### ISSUE THREAD

**Issue by 2741823826GX** [SkyAPM/SkyAPM-dotnet#595]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [✔️] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- 中文：使用IIS托管的.net core程序接入skywalking，在IIS固定回收后，skywalking会采集到两个实例数据（实际上都是一个服务，但是因为重启后导致实例id不一样了，所以在实例列表中会存在两个不同实例id的情况），请问这个场景可以优化一下嘛？
- English：When using a .net core program hosted by IIS to access skywalking, after IIS is fixedly recycled, skywalking will collect data from two instances (actually, they are both one service, but because the instance ID is different after the restart, there will be two different instance IDs in the instance list). Can this scenario be optimized? (Google Translate)

**Comment by wu-sheng** [comment]
That follows the design. We don't ask for the same ID for reboot case. As in today's cloud native env, many things could change due to a pod reboot.

**Comment by 2741823826GX** [comment]
> That follows the design. We don't ask for the same ID for reboot case. As in today's cloud native env, many things could change due to a pod reboot.

ok, thanks

**Comment by wu-sheng** [comment]
You could use https://github.com/SkyAPM/SkyAPM-dotnet/blob/761699c1911dcc6f622eeeb121f60b2b5bda6ecd/src/SkyApm.Utilities.Configuration/ConfigurationBuilderExtensions.cs#L40 to manually set instance name if you have to. However, this would increase the operation complexity.
