### ISSUE TITLE
C#/.NET instrument agent support RabbitMQ or Kafka

### ISSUE THREAD

**Issue by yiyiqian** [SkyAPM/SkyAPM-dotnet#68]
A large number of offline services in our current project are using rabbitMQ. Now C#/.NET instrument agent does not support common queues. I hope skywalking's netcore agent can support this.

**Comment by dcdlove** [comment]
同求

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wu-sheng** [comment]
SkyWalking Satellite is there to provide file-based queue, which is as an alternative of Kafka sender.
