### ISSUE TITLE
Requirement for supporting redis

### ISSUE THREAD

**Issue by kingreatwill** [SkyAPM/SkyAPM-dotnet#71]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

**Comment by zhuoran** [comment]
Please supporting redisson framework ！ thanks

**Comment by MeetOct** [comment]
@zhuoran @kingreatwill 
[here](https://github.com/StackExchange/StackExchange.Redis/issues/833)
