### ISSUE TITLE
可以设置哪些请求不需要追踪吗

### ISSUE THREAD

**Issue by zhaolei0914** [SkyAPM/SkyAPM-dotnet#79]
skywaliking 可以设置哪些请求不需要追踪吗？比如以下的
向注册中心拉取服务列表
向配置中心拉取配置
向各基础组件发送心跳等

**Comment by liuhaoyang** [comment]
I am refactoring the core library of skywalking-netcore. For this feature, I would like to hear your suggestion.

**Comment by 511568420** [comment]
可以把排除的url配置在文件中，通过在AddSkyWalking的方法增加一个参数添加，在内部排除相应的URl跟踪

**Comment by wu-sheng** [comment]
For this feature, you should know, SkyWalking javaagent only considers this feature as an optional plugin. Because even you just set a single exclude rule, the core must do string match every time. Also the cost goes with the number of rules.

So, be careful.

**Comment by liuhaoyang** [comment]
In v0.9.0, we have provided an extension interface for sampling, and you can write your own filtering logic by implementing the [ISamplingInterceptor](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Abstractions/Tracing/ISamplingInterceptor.cs) interface.
