### ISSUE TITLE
Please consider configuration from the configuration center

### ISSUE THREAD

**Issue by beckjin** [SkyAPM/SkyAPM-dotnet#98]
![default](https://user-images.githubusercontent.com/7261408/47604869-a87fca80-da31-11e8-84eb-b44bb225e002.PNG)

It is possible that configuration is not through appsettings.json, but through configuration center.

**Comment by liuhaoyang** [comment]
If you need to load the configuration from the config center, you can implement a custom IConfigAccessor (such as ConfigCenterAccessor) and register it to the DI.

**Comment by beckjin** [comment]
You're right, thank you.

**Comment by liuhaoyang** [comment]
Will provide built-in configuration extensions instead of just reimplementing `IConfigAccessor`

**Comment by wu-sheng** [comment]
.net intend to provide this officially?

**Comment by liuhaoyang** [comment]
> .net intend to provide this officially?

In the micro-service scenario, people prefer to use the config-center to centrally store the application configuration. I think it makes sense to provide the ability to load the agent-config from the config center.

**Comment by wu-sheng** [comment]
Which config center do you prefer? I am thinking to provide such feature in java agent too.

**Comment by beckjin** [comment]
apollo

**Comment by liuhaoyang** [comment]
> Which config center do you prefer? I am thinking to provide such feature in java agent too.

My suggestion is that we only provide the interface for third-party configuration loading, and give the specific config-center implementation to the user. How about?

**Comment by ElderJames** [comment]
That is, you can implement an `IAdditionalConfigurationSource` to fit your own configuration source.
